import {
  getAccountsResource,
  postAccountsResource,
  deleteAccountsResource,
  postAccountEmailChangeResource,
  postAccountEmailVerifyResource,
  getAccountIntegrationsResource,
  deleteAccountIntegrationsResource,
  postAccountOtpResource,
  putAccountOtpResource,
  deleteAccountOtpResource,
  postAccountPasswordResetResource,
  getAccountSettingResource,
  putAccountSettingResource,
  deleteAccountSettingResource,
  getAccountSubsResource,
  putAccountSubsResource,
  getAccountSubResource,
  postAccountSubResource,
  deleteAccountSubResource,
  getAccountUsersResource,
  putAccountUsersResource,
  getAccountUserResource,
  postAccountUserResource,
  deleteAccountUserResource,
  getAddressesResource,
  putAddressesResource,
  getAddressTokenResource,
  getAddressTokenRedeemResource,
  postAddressTokenRedeemResource,
  postAddressResource,
  deleteAddressResource,
  getAddressReservationsResource,
  postAddressReservationIssueResource,
  postAddressReservationRevokeResource,
  postReservationAccessTimesUpdateResource,
  getAddressTokensResource,
  getAddressUnitsResource,
  putAddressUnitsResource,
  deleteAddressUnitsResource,
  deleteAddressUnitResource,
  getDecentralWebhooksResource,
  putDecentralWebhooksResource,
  deleteDecentralWebhookResource,
  getApiKeysResource,
  putApiKeysResource,
  postApiKeyResource,
  deleteApiKeyResource,
  getApiKeyAdvancedResource,
  postApiKeyAdvancedResource,
  putApiKeyAdvancedResource,
  deleteApiKeyAdvancedResource,
  postApiKeyAdvancedReactivateResource,
  getApiKeyTokensResource,
  putApiKeyTokensResource,
  postApiKeyTokenResource,
  deleteApiKeyTokenResource,
  getWebhookLogsResource,
  postSmartlockBulkWebConfigResource,
  getCompaniesResource,
  getNotificationsResource,
  putNotificationsResource,
  getNotificationResource,
  postNotificationResource,
  deleteNotificationResource,
  getOpenerBrandsResource,
  getOpenerBrandResource,
  getOpenerIntercomsResource,
  getOpenerIntercomResource,
  getServicesResource,
  getServiceResource,
  postServiceLinkResource,
  postServiceSyncResource,
  postServiceUnlinkResource,
  getSmartlocksResource,
  getSmartlocksAuthsResource,
  postSmartlocksAuthsResource,
  putSmartlocksAuthsResource,
  deleteSmartlocksAuthsResource,
  putSmartlockAuthsAdvancedResource,
  getSmartlocksLogsResource,
  getSmartlockResource,
  postSmartlockResource,
  deleteSmartlockResource,
  postSmartlockActionResource,
  postSmartlockActionAdvancedResource,
  postSmartlockLockActionResource,
  postSmartlockLockActionAdvancedResource,
  postSmartlockUnlockActionResource,
  postSmartlockUnlockActionAdvancedResource,
  postSmartlockAdminPinResource,
  postSmartlockAdvancedConfigResource,
  postSmartlockOpenerAdvancedConfigResource,
  postSmartdoorAdvancedConfigResource,
  getSmartlockAuthsResource,
  putSmartlockAuthsResource,
  postSmartlockAuthWithSharedKeyResource,
  getSmartlockAuthResource,
  postSmartlockAuthResource,
  deleteSmartlockAuthResource,
  postSmartlockConfigResource,
  getSmartlockLogsResource,
  postSmartlockSyncResource,
  postSmartlockWebConfigResource,
} from "./components";

export const operationsByPath = {
  "GET /account": getAccountsResource,
  "POST /account": postAccountsResource,
  "DELETE /account": deleteAccountsResource,
  "POST /account/email/change": postAccountEmailChangeResource,
  "POST /account/email/verify": postAccountEmailVerifyResource,
  "GET /account/integration": getAccountIntegrationsResource,
  "DELETE /account/integration": deleteAccountIntegrationsResource,
  "POST /account/otp": postAccountOtpResource,
  "PUT /account/otp": putAccountOtpResource,
  "DELETE /account/otp": deleteAccountOtpResource,
  "POST /account/password/reset": postAccountPasswordResetResource,
  "GET /account/setting": getAccountSettingResource,
  "PUT /account/setting": putAccountSettingResource,
  "DELETE /account/setting": deleteAccountSettingResource,
  "GET /account/sub": getAccountSubsResource,
  "PUT /account/sub": putAccountSubsResource,
  "GET /account/sub/{accountId}": getAccountSubResource,
  "POST /account/sub/{accountId}": postAccountSubResource,
  "DELETE /account/sub/{accountId}": deleteAccountSubResource,
  "GET /account/user": getAccountUsersResource,
  "PUT /account/user": putAccountUsersResource,
  "GET /account/user/{accountUserId}": getAccountUserResource,
  "POST /account/user/{accountUserId}": postAccountUserResource,
  "DELETE /account/user/{accountUserId}": deleteAccountUserResource,
  "GET /address": getAddressesResource,
  "PUT /address": putAddressesResource,
  "GET /address/token/{id}": getAddressTokenResource,
  "GET /address/token/{id}/redeem": getAddressTokenRedeemResource,
  "POST /address/token/{id}/redeem": postAddressTokenRedeemResource,
  "POST /address/{addressId}": postAddressResource,
  "DELETE /address/{addressId}": deleteAddressResource,
  "GET /address/{addressId}/reservation": getAddressReservationsResource,
  "POST /address/{addressId}/reservation/{id}/issue":
    postAddressReservationIssueResource,
  "POST /address/{addressId}/reservation/{id}/revoke":
    postAddressReservationRevokeResource,
  "POST /address/{addressId}/reservation/{id}/update/accesstimes":
    postReservationAccessTimesUpdateResource,
  "GET /address/{addressId}/token": getAddressTokensResource,
  "GET /address/{addressId}/unit": getAddressUnitsResource,
  "PUT /address/{addressId}/unit": putAddressUnitsResource,
  "DELETE /address/{addressId}/unit": deleteAddressUnitsResource,
  "DELETE /address/{addressId}/unit/{id}": deleteAddressUnitResource,
  "GET /api/decentralWebhook": getDecentralWebhooksResource,
  "PUT /api/decentralWebhook": putDecentralWebhooksResource,
  "DELETE /api/decentralWebhook/{id}": deleteDecentralWebhookResource,
  "GET /api/key": getApiKeysResource,
  "PUT /api/key": putApiKeysResource,
  "POST /api/key/{apiKeyId}": postApiKeyResource,
  "DELETE /api/key/{apiKeyId}": deleteApiKeyResource,
  "GET /api/key/{apiKeyId}/advanced": getApiKeyAdvancedResource,
  "POST /api/key/{apiKeyId}/advanced": postApiKeyAdvancedResource,
  "PUT /api/key/{apiKeyId}/advanced": putApiKeyAdvancedResource,
  "DELETE /api/key/{apiKeyId}/advanced": deleteApiKeyAdvancedResource,
  "POST /api/key/{apiKeyId}/advanced/reactivate":
    postApiKeyAdvancedReactivateResource,
  "GET /api/key/{apiKeyId}/token": getApiKeyTokensResource,
  "PUT /api/key/{apiKeyId}/token": putApiKeyTokensResource,
  "POST /api/key/{apiKeyId}/token/{id}": postApiKeyTokenResource,
  "DELETE /api/key/{apiKeyId}/token/{id}": deleteApiKeyTokenResource,
  "GET /api/key/{apiKeyId}/webhook/logs": getWebhookLogsResource,
  "POST /bulk-web-config": postSmartlockBulkWebConfigResource,
  "GET /company": getCompaniesResource,
  "GET /notification": getNotificationsResource,
  "PUT /notification": putNotificationsResource,
  "GET /notification/{notificationId}": getNotificationResource,
  "POST /notification/{notificationId}": postNotificationResource,
  "DELETE /notification/{notificationId}": deleteNotificationResource,
  "GET /opener/brand": getOpenerBrandsResource,
  "GET /opener/brand/{brandId}": getOpenerBrandResource,
  "GET /opener/intercom": getOpenerIntercomsResource,
  "GET /opener/intercom/{intercomId}": getOpenerIntercomResource,
  "GET /service": getServicesResource,
  "GET /service/{serviceId}": getServiceResource,
  "POST /service/{serviceId}/link": postServiceLinkResource,
  "POST /service/{serviceId}/sync": postServiceSyncResource,
  "POST /service/{serviceId}/unlink": postServiceUnlinkResource,
  "GET /smartlock": getSmartlocksResource,
  "GET /smartlock/auth": getSmartlocksAuthsResource,
  "POST /smartlock/auth": postSmartlocksAuthsResource,
  "PUT /smartlock/auth": putSmartlocksAuthsResource,
  "DELETE /smartlock/auth": deleteSmartlocksAuthsResource,
  "PUT /smartlock/auth/advanced": putSmartlockAuthsAdvancedResource,
  "GET /smartlock/log": getSmartlocksLogsResource,
  "GET /smartlock/{smartlockId}": getSmartlockResource,
  "POST /smartlock/{smartlockId}": postSmartlockResource,
  "DELETE /smartlock/{smartlockId}": deleteSmartlockResource,
  "POST /smartlock/{smartlockId}/action": postSmartlockActionResource,
  "POST /smartlock/{smartlockId}/action/advanced":
    postSmartlockActionAdvancedResource,
  "POST /smartlock/{smartlockId}/action/lock": postSmartlockLockActionResource,
  "POST /smartlock/{smartlockId}/action/lock/advanced":
    postSmartlockLockActionAdvancedResource,
  "POST /smartlock/{smartlockId}/action/unlock":
    postSmartlockUnlockActionResource,
  "POST /smartlock/{smartlockId}/action/unlock/advanced":
    postSmartlockUnlockActionAdvancedResource,
  "POST /smartlock/{smartlockId}/admin/pin": postSmartlockAdminPinResource,
  "POST /smartlock/{smartlockId}/advanced/config":
    postSmartlockAdvancedConfigResource,
  "POST /smartlock/{smartlockId}/advanced/openerconfig":
    postSmartlockOpenerAdvancedConfigResource,
  "POST /smartlock/{smartlockId}/advanced/smartdoorconfig":
    postSmartdoorAdvancedConfigResource,
  "GET /smartlock/{smartlockId}/auth": getSmartlockAuthsResource,
  "PUT /smartlock/{smartlockId}/auth": putSmartlockAuthsResource,
  "POST /smartlock/{smartlockId}/auth/advanced/sharedkey":
    postSmartlockAuthWithSharedKeyResource,
  "GET /smartlock/{smartlockId}/auth/{id}": getSmartlockAuthResource,
  "POST /smartlock/{smartlockId}/auth/{id}": postSmartlockAuthResource,
  "DELETE /smartlock/{smartlockId}/auth/{id}": deleteSmartlockAuthResource,
  "POST /smartlock/{smartlockId}/config": postSmartlockConfigResource,
  "GET /smartlock/{smartlockId}/log": getSmartlockLogsResource,
  "POST /smartlock/{smartlockId}/sync": postSmartlockSyncResource,
  "POST /smartlock/{smartlockId}/web/config": postSmartlockWebConfigResource,
};
