import {
  listSites,
  createSite,
  getSite,
  updateSite,
  deleteSite,
  provisionSiteTLSCertificate,
  showSiteTLSCertificate,
  getEnvVars,
  createEnvVars,
  getSiteEnvVars,
  getEnvVar,
  updateEnvVar,
  setEnvVarValue,
  deleteEnvVar,
  deleteEnvVarValue,
  listSiteForms,
  deleteSiteForm,
  listSiteSubmissions,
  listSiteFiles,
  listSiteAssets,
  createSiteAsset,
  getSiteAssetInfo,
  updateSiteAsset,
  deleteSiteAsset,
  getSiteAssetPublicSignature,
  getSiteFileByPathName,
  purgeCache,
  listSiteSnippets,
  createSiteSnippet,
  getSiteSnippet,
  updateSiteSnippet,
  deleteSiteSnippet,
  getSiteMetadata,
  updateSiteMetadata,
  listSiteBuildHooks,
  createSiteBuildHook,
  getSiteBuildHook,
  updateSiteBuildHook,
  deleteSiteBuildHook,
  listSiteDeploys,
  createSiteDeploy,
  getSiteDeploy,
  updateSiteDeploy,
  deleteSiteDeploy,
  cancelSiteDeploy,
  restoreSiteDeploy,
  listSiteBuilds,
  createSiteBuild,
  listSiteDeployedBranches,
  unlinkSiteRepo,
  getSiteBuild,
  updateSiteBuildLog,
  notifyBuildStart,
  getAccountBuildStatus,
  getDNSForSite,
  configureDNSForSite,
  rollbackSiteDeploy,
  getDeploy,
  deleteDeploy,
  lockDeploy,
  unlockDeploy,
  uploadDeployFile,
  uploadDeployFunction,
  updatePlugin,
  getLatestPluginRuns,
  createPluginRun,
  listFormSubmissions,
  listHooksBySiteId,
  createHookBySiteId,
  getHook,
  updateHook,
  deleteHook,
  enableHook,
  listHookTypes,
  createTicket,
  showTicket,
  exchangeTicket,
  listDeployKeys,
  createDeployKey,
  getDeployKey,
  deleteDeployKey,
  createSiteInTeam,
  listSitesForAccount,
  listMembersForAccount,
  addMemberToAccount,
  getAccountMember,
  updateAccountMember,
  removeAccountMember,
  listPaymentMethodsForUser,
  listAccountTypesForUser,
  listAccountsForUser,
  createAccount,
  getAccount,
  updateAccount,
  cancelAccount,
  listAccountAuditEvents,
  listFormSubmission,
  deleteSubmission,
  listServiceInstancesForSite,
  createServiceInstance,
  showServiceInstance,
  updateServiceInstance,
  deleteServiceInstance,
  getServices,
  showService,
  showServiceManifest,
  getCurrentUser,
  createSplitTest,
  getSplitTests,
  updateSplitTest,
  getSplitTest,
  enableSplitTest,
  disableSplitTest,
  createDnsZone,
  getDnsZones,
  getDnsZone,
  deleteDnsZone,
  transferDnsZone,
  getDnsRecords,
  createDnsRecord,
  getIndividualDnsRecord,
  deleteDnsRecord
} from './components';

export const operationsByPath = {
  'GET /sites': listSites,
  'POST /sites': createSite,
  'GET /sites/{site_id}': getSite,
  'PATCH /sites/{site_id}': updateSite,
  'DELETE /sites/{site_id}': deleteSite,
  'POST /sites/{site_id}/ssl': provisionSiteTLSCertificate,
  'GET /sites/{site_id}/ssl': showSiteTLSCertificate,
  'GET /accounts/{account_id}/env': getEnvVars,
  'POST /accounts/{account_id}/env': createEnvVars,
  'GET /api/v1/sites/{site_id}/env': getSiteEnvVars,
  'GET /accounts/{account_id}/env/{key}': getEnvVar,
  'PUT /accounts/{account_id}/env/{key}': updateEnvVar,
  'PATCH /accounts/{account_id}/env/{key}': setEnvVarValue,
  'DELETE /accounts/{account_id}/env/{key}': deleteEnvVar,
  'DELETE /accounts/{account_id}/env/{key}/value/{id}': deleteEnvVarValue,
  'GET /sites/{site_id}/forms': listSiteForms,
  'DELETE /sites/{site_id}/forms/{form_id}': deleteSiteForm,
  'GET /sites/{site_id}/submissions': listSiteSubmissions,
  'GET /sites/{site_id}/files': listSiteFiles,
  'GET /sites/{site_id}/assets': listSiteAssets,
  'POST /sites/{site_id}/assets': createSiteAsset,
  'GET /sites/{site_id}/assets/{asset_id}': getSiteAssetInfo,
  'PUT /sites/{site_id}/assets/{asset_id}': updateSiteAsset,
  'DELETE /sites/{site_id}/assets/{asset_id}': deleteSiteAsset,
  'GET /sites/{site_id}/assets/{asset_id}/public_signature': getSiteAssetPublicSignature,
  'GET /sites/{site_id}/files/{file_path}': getSiteFileByPathName,
  'POST /purge': purgeCache,
  'GET /sites/{site_id}/snippets': listSiteSnippets,
  'POST /sites/{site_id}/snippets': createSiteSnippet,
  'GET /sites/{site_id}/snippets/{snippet_id}': getSiteSnippet,
  'PUT /sites/{site_id}/snippets/{snippet_id}': updateSiteSnippet,
  'DELETE /sites/{site_id}/snippets/{snippet_id}': deleteSiteSnippet,
  'GET /sites/{site_id}/metadata': getSiteMetadata,
  'PUT /sites/{site_id}/metadata': updateSiteMetadata,
  'GET /sites/{site_id}/build_hooks': listSiteBuildHooks,
  'POST /sites/{site_id}/build_hooks': createSiteBuildHook,
  'GET /sites/{site_id}/build_hooks/{id}': getSiteBuildHook,
  'PUT /sites/{site_id}/build_hooks/{id}': updateSiteBuildHook,
  'DELETE /sites/{site_id}/build_hooks/{id}': deleteSiteBuildHook,
  'GET /sites/{site_id}/deploys': listSiteDeploys,
  'POST /sites/{site_id}/deploys': createSiteDeploy,
  'GET /sites/{site_id}/deploys/{deploy_id}': getSiteDeploy,
  'PUT /sites/{site_id}/deploys/{deploy_id}': updateSiteDeploy,
  'DELETE /sites/{site_id}/deploys/{deploy_id}': deleteSiteDeploy,
  'POST /deploys/{deploy_id}/cancel': cancelSiteDeploy,
  'POST /sites/{site_id}/deploys/{deploy_id}/restore': restoreSiteDeploy,
  'GET /sites/{site_id}/builds': listSiteBuilds,
  'POST /sites/{site_id}/builds': createSiteBuild,
  'GET /sites/{site_id}/deployed-branches': listSiteDeployedBranches,
  'PUT /sites/{site_id}/unlink_repo': unlinkSiteRepo,
  'GET /builds/{build_id}': getSiteBuild,
  'POST /builds/{build_id}/log': updateSiteBuildLog,
  'POST /builds/{build_id}/start': notifyBuildStart,
  'GET /{account_id}/builds/status': getAccountBuildStatus,
  'GET /sites/{site_id}/dns': getDNSForSite,
  'PUT /sites/{site_id}/dns': configureDNSForSite,
  'PUT /sites/{site_id}/rollback': rollbackSiteDeploy,
  'GET /deploys/{deploy_id}': getDeploy,
  'DELETE /deploys/{deploy_id}': deleteDeploy,
  'POST /deploys/{deploy_id}/lock': lockDeploy,
  'POST /deploys/{deploy_id}/unlock': unlockDeploy,
  'PUT /deploys/{deploy_id}/files/{path}': uploadDeployFile,
  'PUT /deploys/{deploy_id}/functions/{name}': uploadDeployFunction,
  'PUT /sites/{site_id}/plugins/{package}': updatePlugin,
  'GET /sites/{site_id}/plugin_runs/latest': getLatestPluginRuns,
  'POST /deploys/{deploy_id}/plugin_runs': createPluginRun,
  'GET /forms/{form_id}/submissions': listFormSubmissions,
  'GET /hooks': listHooksBySiteId,
  'POST /hooks': createHookBySiteId,
  'GET /hooks/{hook_id}': getHook,
  'PUT /hooks/{hook_id}': updateHook,
  'DELETE /hooks/{hook_id}': deleteHook,
  'POST /hooks/{hook_id}/enable': enableHook,
  'GET /hooks/types': listHookTypes,
  'POST /oauth/tickets': createTicket,
  'GET /oauth/tickets/{ticket_id}': showTicket,
  'POST /oauth/tickets/{ticket_id}/exchange': exchangeTicket,
  'GET /deploy_keys': listDeployKeys,
  'POST /deploy_keys': createDeployKey,
  'GET /deploy_keys/{key_id}': getDeployKey,
  'DELETE /deploy_keys/{key_id}': deleteDeployKey,
  'POST /{account_slug}/sites': createSiteInTeam,
  'GET /{account_slug}/sites': listSitesForAccount,
  'GET /{account_slug}/members': listMembersForAccount,
  'POST /{account_slug}/members': addMemberToAccount,
  'GET /{account_slug}/members/{member_id}': getAccountMember,
  'PUT /{account_slug}/members/{member_id}': updateAccountMember,
  'DELETE /{account_slug}/members/{member_id}': removeAccountMember,
  'GET /billing/payment_methods': listPaymentMethodsForUser,
  'GET /accounts/types': listAccountTypesForUser,
  'GET /accounts': listAccountsForUser,
  'POST /accounts': createAccount,
  'GET /accounts/{account_id}': getAccount,
  'PUT /accounts/{account_id}': updateAccount,
  'DELETE /accounts/{account_id}': cancelAccount,
  'GET /accounts/{account_id}/audit': listAccountAuditEvents,
  'GET /submissions/{submission_id}': listFormSubmission,
  'DELETE /submissions/{submission_id}': deleteSubmission,
  'GET /sites/{site_id}/service-instances': listServiceInstancesForSite,
  'POST /sites/{site_id}/services/{addon}/instances': createServiceInstance,
  'GET /sites/{site_id}/services/{addon}/instances/{instance_id}': showServiceInstance,
  'PUT /sites/{site_id}/services/{addon}/instances/{instance_id}': updateServiceInstance,
  'DELETE /sites/{site_id}/services/{addon}/instances/{instance_id}': deleteServiceInstance,
  'GET /services/': getServices,
  'GET /services/{addonName}': showService,
  'GET /services/{addonName}/manifest': showServiceManifest,
  'GET /user': getCurrentUser,
  'POST /sites/{site_id}/traffic_splits': createSplitTest,
  'GET /sites/{site_id}/traffic_splits': getSplitTests,
  'PUT /sites/{site_id}/traffic_splits/{split_test_id}': updateSplitTest,
  'GET /sites/{site_id}/traffic_splits/{split_test_id}': getSplitTest,
  'POST /sites/{site_id}/traffic_splits/{split_test_id}/publish': enableSplitTest,
  'POST /sites/{site_id}/traffic_splits/{split_test_id}/unpublish': disableSplitTest,
  'POST /dns_zones': createDnsZone,
  'GET /dns_zones': getDnsZones,
  'GET /dns_zones/{zone_id}': getDnsZone,
  'DELETE /dns_zones/{zone_id}': deleteDnsZone,
  'PUT /dns_zones/{zone_id}/transfer': transferDnsZone,
  'GET /dns_zones/{zone_id}/dns_records': getDnsRecords,
  'POST /dns_zones/{zone_id}/dns_records': createDnsRecord,
  'GET /dns_zones/{zone_id}/dns_records/{dns_record_id}': getIndividualDnsRecord,
  'DELETE /dns_zones/{zone_id}/dns_records/{dns_record_id}': deleteDnsRecord
};
