/**
 * Generated by @openapi-codegen
 *
 * @version 2.23.1
 */
/**
 * @format int32
 */
export type Page = number;

/**
 * @format int32
 */
export type PerPage = number;

export type RetryCount = number;
