/**
 * Generated by @openapi-codegen
 *
 * @version 2.40
 */
import type * as Schemas from './schemas';

export type DataSetValueQueryParamsCc = Schemas.UIDCategoryCombo;

export type DataSetValueQueryParamsCp = Schemas.UIDCategoryOption;

export type DataSetValueQueryParamsDs = Schemas.UIDDataElement;

export type DataSetValueQueryParamsOu = Schemas.UIDOrganisationUnit;

/**
 * @format period
 */
export type DataSetValueQueryParamsPe = string;

export type DataValueQueryParamsCc = Schemas.UIDCategoryCombo;

export type DataValueQueryParamsCo = Schemas.UIDCategoryOptionCombo;

export type DataValueQueryParamsCp = Schemas.UIDCategoryOption;

export type DataValueQueryParamsDe = Schemas.UIDDataElement;

export type DataValueQueryParamsOu = Schemas.UIDOrganisationUnit;

/**
 * @format period
 */
export type DataValueQueryParamsPe = string;

export type GistParamsAbsoluteUrls = boolean;

export type GistParamsAuto = 'XL' | 'L' | 'M' | 'S' | 'XS';

export type GistParamsDescribe = boolean;

export type GistParamsFields = string;

export type GistParamsFilter = string;

export type GistParamsHeadless = boolean;

export type GistParamsInverse = boolean;

export type GistParamsLocale = string;

export type GistParamsOrder = string;

/**
 * @format int32
 */
export type GistParamsPage = number;

/**
 * @format int32
 */
export type GistParamsPageSize = number;

export type GistParamsReferences = boolean;

export type GistParamsRootJunction = 'AND' | 'OR';

export type GistParamsTotal = boolean;

export type GistParamsTranslate = boolean;

export type ImportOptionsAsync = boolean;

export type ImportOptionsDataSet = string;

export type ImportOptionsDatasetAllowsPeriods = boolean;

export type ImportOptionsDryRun = boolean;

export type ImportOptionsFilename = string;

export type ImportOptionsFirstRowIsHeader = boolean;

export type ImportOptionsForce = boolean;

export type ImportOptionsIdSchemes = Schemas.IdSchemes;

export type ImportOptionsIgnoreEmptyCollection = boolean;

export type ImportOptionsImportStrategy =
  | 'CREATE'
  | 'UPDATE'
  | 'CREATE_AND_UPDATE'
  | 'DELETE'
  | 'SYNC'
  | 'NEW_AND_UPDATES'
  | 'NEW'
  | 'UPDATES'
  | 'DELETES';

export type ImportOptionsMergeDataValues = boolean;

export type ImportOptionsMergeMode = 'MERGE_ALWAYS' | 'MERGE_IF_NOT_NULL' | 'MERGE' | 'REPLACE' | 'NONE';

export type ImportOptionsNotificationLevel = 'OFF' | 'DEBUG' | 'LOOP' | 'INFO' | 'WARN' | 'ERROR';

export type ImportOptionsPreheatCache = boolean;

export type ImportOptionsReportMode = 'FULL' | 'ERRORS' | 'ERRORS_NOT_OWNER' | 'DEBUG';

export type ImportOptionsRequireAttributeOptionCombo = boolean;

export type ImportOptionsRequireCategoryOptionCombo = boolean;

export type ImportOptionsSharing = boolean;

export type ImportOptionsSkipAudit = boolean;

export type ImportOptionsSkipCache = boolean;

export type ImportOptionsSkipExistingCheck = boolean;

export type ImportOptionsSkipLastUpdated = boolean;

export type ImportOptionsSkipNotifications = boolean;

export type ImportOptionsSkipPatternValidation = boolean;

export type ImportOptionsStrictAttributeOptionCombos = boolean;

export type ImportOptionsStrictCategoryOptionCombos = boolean;

export type ImportOptionsStrictDataElements = boolean;

export type ImportOptionsStrictDataSetApproval = boolean;

export type ImportOptionsStrictDataSetInputPeriods = boolean;

export type ImportOptionsStrictDataSetLocking = boolean;

export type ImportOptionsStrictOrganisationUnits = boolean;

export type ImportOptionsStrictPeriods = boolean;

export type MetadataImportParamsAtomicMode = 'ALL' | 'NONE';

export type MetadataImportParamsFlushMode = 'OBJECT' | 'AUTO';

export type MetadataImportParamsIdentifier = 'UID' | 'CODE';

export type MetadataImportParamsImportMode = 'COMMIT' | 'VALIDATE';

export type MetadataImportParamsImportReportMode = 'FULL' | 'ERRORS' | 'ERRORS_NOT_OWNER' | 'DEBUG';

export type MetadataImportParamsImportStrategy =
  | 'CREATE'
  | 'UPDATE'
  | 'CREATE_AND_UPDATE'
  | 'DELETE'
  | 'SYNC'
  | 'NEW_AND_UPDATES'
  | 'NEW'
  | 'UPDATES'
  | 'DELETES';

export type MetadataImportParamsMergeMode = 'MERGE_ALWAYS' | 'MERGE_IF_NOT_NULL' | 'MERGE' | 'REPLACE' | 'NONE';

export type MetadataImportParamsMetadataSyncImport = boolean;

export type MetadataImportParamsPreheatMode = 'REFERENCE' | 'ALL' | 'NONE';

export type MetadataImportParamsSkipSharing = boolean;

export type MetadataImportParamsSkipTranslation = boolean;

export type MetadataImportParamsSkipValidation = boolean;

export type MetadataImportParamsUserOverrideMode = 'NONE' | 'CURRENT' | 'SELECTED';

export type MinMaxValueQueryParamsCo = Schemas.UIDCategoryOptionCombo;

export type MinMaxValueQueryParamsDe = Schemas.UIDDataElement;

export type MinMaxValueQueryParamsOu = Schemas.UIDOrganisationUnit;

export type OrderParamsOrders = string[];

export type TranslateParamsLocale = string;

export type TranslateParamsTranslate = boolean;

/**
 * @format int32
 */
export type WebOptionsPage = number;

/**
 * @format int32
 */
export type WebOptionsPageSize = number;

export type WebOptionsPaging = boolean;

export type WebOptionsRootJunction = 'AND' | 'OR';
