/**
 * Generated by @openapi-codegen
 *
 * @version 2.40
 */
/**
 * A UID for an CategoryCombo object
 * (Java name `org.hisp.dhis.category.CategoryCombo`)
 *
 * @format uid
 * @pattern ^[0-9a-zA-Z]{11}$
 * @minLength 11
 * @maxLength 11
 * @example iZ9tI8jD7T4
 */
export type DataSetValueQueryParamsCc = string;

/**
 * A UID for an CategoryOption object
 * (Java name `org.hisp.dhis.category.CategoryOption`)
 *
 * @format uid
 * @pattern ^[0-9a-zA-Z]{11}$
 * @minLength 11
 * @maxLength 11
 * @example j0wu64kE8Vc
 */
export type DataSetValueQueryParamsCp = string;

/**
 * A UID for an DataElement object
 * (Java name `org.hisp.dhis.dataelement.DataElement`)
 *
 * @format uid
 * @pattern ^[0-9a-zA-Z]{11}$
 * @minLength 11
 * @maxLength 11
 * @example hX7n8Y4pu89
 */
export type DataSetValueQueryParamsDs = string;

/**
 * A UID for an OrganisationUnit object
 * (Java name `org.hisp.dhis.organisationunit.OrganisationUnit`)
 *
 * @format uid
 * @pattern ^[0-9a-zA-Z]{11}$
 * @minLength 11
 * @maxLength 11
 * @example xj2sS1ni0Q9
 */
export type DataSetValueQueryParamsOu = string;

/**
 * @format period
 */
export type DataSetValueQueryParamsPe = string;

/**
 * A UID for an CategoryCombo object
 * (Java name `org.hisp.dhis.category.CategoryCombo`)
 *
 * @format uid
 * @pattern ^[0-9a-zA-Z]{11}$
 * @minLength 11
 * @maxLength 11
 * @example iZ9tI8jD7T4
 */
export type DataValueQueryParamsCc = string;

/**
 * A UID for an CategoryOptionCombo object
 * (Java name `org.hisp.dhis.category.CategoryOptionCombo`)
 *
 * @format uid
 * @pattern ^[0-9a-zA-Z]{11}$
 * @minLength 11
 * @maxLength 11
 * @example o5Bz19pJ30h
 */
export type DataValueQueryParamsCo = string;

/**
 * A UID for an CategoryOption object
 * (Java name `org.hisp.dhis.category.CategoryOption`)
 *
 * @format uid
 * @pattern ^[0-9a-zA-Z]{11}$
 * @minLength 11
 * @maxLength 11
 * @example j0wu64kE8Vc
 */
export type DataValueQueryParamsCp = string;

/**
 * A UID for an DataElement object
 * (Java name `org.hisp.dhis.dataelement.DataElement`)
 *
 * @format uid
 * @pattern ^[0-9a-zA-Z]{11}$
 * @minLength 11
 * @maxLength 11
 * @example hX7n8Y4pu89
 */
export type DataValueQueryParamsDe = string;

/**
 * A UID for an OrganisationUnit object
 * (Java name `org.hisp.dhis.organisationunit.OrganisationUnit`)
 *
 * @format uid
 * @pattern ^[0-9a-zA-Z]{11}$
 * @minLength 11
 * @maxLength 11
 * @example xj2sS1ni0Q9
 */
export type DataValueQueryParamsOu = string;

/**
 * @format period
 */
export type DataValueQueryParamsPe = string;

/**
 * @default false
 */
export type GistParamsAbsoluteUrls = boolean;

export type GistParamsAuto = 'L' | 'M' | 'S' | 'XL' | 'XS';

/**
 * @default false
 */
export type GistParamsDescribe = boolean;

export type GistParamsFields = string;

export type GistParamsFilter = string;

/**
 * @default false
 */
export type GistParamsHeadless = boolean;

/**
 * @default false
 */
export type GistParamsInverse = boolean;

/**
 * @default
 */
export type GistParamsLocale = string;

export type GistParamsOrder = string;

/**
 * @format int32
 * @default 1
 */
export type GistParamsPage = number;

export type GistParamsPageListName = string;

/**
 * @format int32
 * @default 50
 */
export type GistParamsPageSize = number;

/**
 * @default true
 */
export type GistParamsReferences = boolean;

/**
 * @default AND
 */
export type GistParamsRootJunction = 'AND' | 'OR';

/**
 * @default false
 */
export type GistParamsTotal = boolean;

/**
 * @default true
 */
export type GistParamsTranslate = boolean;

/**
 * @default false
 */
export type ImportOptionsAsync = boolean;

export type ImportOptionsCategoryIdScheme = string;

export type ImportOptionsCategoryOptionComboIdScheme = string;

export type ImportOptionsCategoryOptionIdScheme = string;

export type ImportOptionsDataElementIdScheme = string;

export type ImportOptionsDataSet = string;

export type ImportOptionsDataSetIdScheme = string;

/**
 * @default false
 */
export type ImportOptionsDatasetAllowsPeriods = boolean;

/**
 * @default false
 */
export type ImportOptionsDryRun = boolean;

export type ImportOptionsEventIdScheme = string;

export type ImportOptionsFilename = string;

/**
 * @default true
 */
export type ImportOptionsFirstRowIsHeader = boolean;

/**
 * @default false
 */
export type ImportOptionsForce = boolean;

export type ImportOptionsIdScheme = string;

/**
 * @default false
 */
export type ImportOptionsIgnoreEmptyCollection = boolean;

/**
 * @default CREATE_AND_UPDATE
 */
export type ImportOptionsImportStrategy =
  | 'CREATE'
  | 'CREATE_AND_UPDATE'
  | 'DELETE'
  | 'DELETES'
  | 'NEW'
  | 'NEW_AND_UPDATES'
  | 'SYNC'
  | 'UPDATE'
  | 'UPDATES';

/**
 * @default false
 */
export type ImportOptionsMergeDataValues = boolean;

/**
 * @default REPLACE
 */
export type ImportOptionsMergeMode = 'MERGE' | 'MERGE_ALWAYS' | 'MERGE_IF_NOT_NULL' | 'NONE' | 'REPLACE';

export type ImportOptionsNotificationLevel = 'DEBUG' | 'ERROR' | 'INFO' | 'LOOP' | 'OFF' | 'WARN';

export type ImportOptionsOrgUnitIdScheme = string;

export type ImportOptionsPreheatCache = boolean;

export type ImportOptionsProgramIdScheme = string;

export type ImportOptionsProgramStageIdScheme = string;

/**
 * @default FULL
 */
export type ImportOptionsReportMode = 'DEBUG' | 'ERRORS' | 'ERRORS_NOT_OWNER' | 'FULL';

/**
 * @default false
 */
export type ImportOptionsRequireAttributeOptionCombo = boolean;

/**
 * @default false
 */
export type ImportOptionsRequireCategoryOptionCombo = boolean;

/**
 * @default false
 */
export type ImportOptionsSharing = boolean;

/**
 * @default false
 */
export type ImportOptionsSkipAudit = boolean;

/**
 * @default false
 */
export type ImportOptionsSkipCache = boolean;

/**
 * @default false
 */
export type ImportOptionsSkipExistingCheck = boolean;

/**
 * @default false
 */
export type ImportOptionsSkipLastUpdated = boolean;

/**
 * @default false
 */
export type ImportOptionsSkipNotifications = boolean;

/**
 * @default false
 */
export type ImportOptionsSkipPatternValidation = boolean;

/**
 * @default false
 */
export type ImportOptionsStrictAttributeOptionCombos = boolean;

/**
 * @default false
 */
export type ImportOptionsStrictCategoryOptionCombos = boolean;

/**
 * @default false
 */
export type ImportOptionsStrictDataElements = boolean;

/**
 * @default false
 */
export type ImportOptionsStrictDataSetApproval = boolean;

/**
 * @default false
 */
export type ImportOptionsStrictDataSetInputPeriods = boolean;

/**
 * @default false
 */
export type ImportOptionsStrictDataSetLocking = boolean;

/**
 * @default false
 */
export type ImportOptionsStrictOrganisationUnits = boolean;

/**
 * @default false
 */
export type ImportOptionsStrictPeriods = boolean;

export type ImportOptionsTrackedEntityAttributeIdScheme = string;

export type ImportOptionsTrackedEntityIdScheme = string;

/**
 * @default ALL
 */
export type MetadataImportParamsAtomicMode = 'ALL' | 'NONE';

/**
 * @default AUTO
 */
export type MetadataImportParamsFlushMode = 'AUTO' | 'OBJECT';

/**
 * @default UID
 */
export type MetadataImportParamsIdentifier = 'CODE' | 'UID';

/**
 * @default COMMIT
 */
export type MetadataImportParamsImportMode = 'COMMIT' | 'VALIDATE';

/**
 * @default ERRORS
 */
export type MetadataImportParamsImportReportMode = 'DEBUG' | 'ERRORS' | 'ERRORS_NOT_OWNER' | 'FULL';

/**
 * @default CREATE_AND_UPDATE
 */
export type MetadataImportParamsImportStrategy =
  | 'CREATE'
  | 'CREATE_AND_UPDATE'
  | 'DELETE'
  | 'DELETES'
  | 'NEW'
  | 'NEW_AND_UPDATES'
  | 'SYNC'
  | 'UPDATE'
  | 'UPDATES';

/**
 * @default REPLACE
 */
export type MetadataImportParamsMergeMode = 'MERGE' | 'MERGE_ALWAYS' | 'MERGE_IF_NOT_NULL' | 'NONE' | 'REPLACE';

/**
 * @default false
 */
export type MetadataImportParamsMetadataSyncImport = boolean;

/**
 * @default REFERENCE
 */
export type MetadataImportParamsPreheatMode = 'ALL' | 'NONE' | 'REFERENCE';

/**
 * @default false
 */
export type MetadataImportParamsSkipSharing = boolean;

/**
 * @default false
 */
export type MetadataImportParamsSkipTranslation = boolean;

/**
 * @default false
 */
export type MetadataImportParamsSkipValidation = boolean;

/**
 * @default NONE
 */
export type MetadataImportParamsUserOverrideMode = 'CURRENT' | 'NONE' | 'SELECTED';

/**
 * A UID for an CategoryOptionCombo object
 * (Java name `org.hisp.dhis.category.CategoryOptionCombo`)
 *
 * @format uid
 * @pattern ^[0-9a-zA-Z]{11}$
 * @minLength 11
 * @maxLength 11
 * @example o5Bz19pJ30h
 */
export type MinMaxValueQueryParamsCo = string;

/**
 * A UID for an DataElement object
 * (Java name `org.hisp.dhis.dataelement.DataElement`)
 *
 * @format uid
 * @pattern ^[0-9a-zA-Z]{11}$
 * @minLength 11
 * @maxLength 11
 * @example hX7n8Y4pu89
 */
export type MinMaxValueQueryParamsDe = string;

/**
 * A UID for an OrganisationUnit object
 * (Java name `org.hisp.dhis.organisationunit.OrganisationUnit`)
 *
 * @format uid
 * @pattern ^[0-9a-zA-Z]{11}$
 * @minLength 11
 * @maxLength 11
 * @example xj2sS1ni0Q9
 */
export type MinMaxValueQueryParamsOu = string;

export type OrderParamsOrders = string[];

export type TranslateParamsLocale = string;

/**
 * @default true
 */
export type TranslateParamsTranslate = boolean;

/**
 * @format int32
 */
export type WebOptionsPage = number;

/**
 * @format int32
 */
export type WebOptionsPageSize = number;

export type WebOptionsPaging = boolean;

export type WebOptionsRootJunction = 'AND' | 'OR';
