import {
  recordEvents,
  status,
  uploadArtifact,
  downloadArtifact,
  artifactQuery,
  createCheck,
  getAllChecks,
  getCheck,
  updateCheck,
  rerequestCheck,
  updateProjectDataCache,
  getDeploymentEvents,
  getDeployment,
  createDeployment,
  cancelDeployment,
  buyDomain,
  checkDomainPrice,
  getRecords,
  createRecord,
  updateRecord,
  removeRecord,
  checkDomainStatus,
  getDomainTransfer,
  getDomainConfig,
  getDomain,
  getDomains,
  createOrTransferDomain,
  patchDomain,
  deleteDomain,
  getEdgeConfigs,
  createEdgeConfig,
  getEdgeConfig,
  updateEdgeConfig,
  deleteEdgeConfig,
  getEdgeConfigItems,
  patchtEdgeConfigItems,
  getEdgeConfigItem,
  getEdgeConfigTokens,
  deleteEdgeConfigTokens,
  getEdgeConfigToken,
  createEdgeConfigToken,
  listUserEvents,
  getConfigurations,
  getConfiguration,
  deleteConfiguration,
  getIntegrationLogDrains,
  createLogDrain,
  deleteIntegrationLogDrain,
  gitNamespaces,
  searchRepo,
  getConfigurableLogDrain,
  deleteConfigurableLogDrain,
  getConfigurableLogDrains,
  createConfigurableLogDrain,
  getProjectMembers,
  addProjectMember,
  removeProjectMember,
  getProjects,
  createProject,
  getProject,
  updateProject,
  deleteProject,
  getProjectDomains,
  getProjectDomain,
  updateProjectDomain,
  removeProjectDomain,
  addProjectDomain,
  verifyProjectDomain,
  filterProjectEnvs,
  getProjectEnv,
  createProjectEnv,
  removeProjectEnv,
  editProjectEnv,
  getTeamMembers,
  inviteUserToTeam,
  requestAccessToTeam,
  getTeamAccessRequest,
  joinTeam,
  updateTeamMember,
  removeTeamMember,
  getTeam,
  patchTeam,
  getTeams,
  createTeam,
  deleteTeam,
  deleteTeamInviteCode,
  uploadFile,
  getAuthUser,
  requestDelete,
  listAuthTokens,
  createAuthToken,
  getAuthToken,
  deleteAuthToken,
  createWebhook,
  getWebhooks,
  getWebhook,
  deleteWebhook,
  listAliases,
  getAlias,
  deleteAlias,
  listDeploymentAliases,
  assignAlias,
  getCertById,
  removeCert,
  issueCert,
  uploadCert,
  listDeploymentFiles,
  getDeploymentFileContents,
  getDeployments,
  verifyToken,
  emailLogin,
  deleteDeployment,
  getSecrets,
  createSecret,
  renameSecret,
  getSecret,
  deleteSecret
} from './components';

export const operationsByPath = {
  'POST /v8/artifacts/events': recordEvents,
  'GET /v8/artifacts/status': status,
  'PUT /v8/artifacts/{hash}': uploadArtifact,
  'GET /v8/artifacts/{hash}': downloadArtifact,
  'POST /v8/artifacts': artifactQuery,
  'POST /v1/deployments/{deploymentId}/checks': createCheck,
  'GET /v1/deployments/{deploymentId}/checks': getAllChecks,
  'GET /v1/deployments/{deploymentId}/checks/{checkId}': getCheck,
  'PATCH /v1/deployments/{deploymentId}/checks/{checkId}': updateCheck,
  'POST /v1/deployments/{deploymentId}/checks/{checkId}/rerequest': rerequestCheck,
  'PATCH /v1/data-cache/projects/{projectId}': updateProjectDataCache,
  'GET /v2/deployments/{idOrUrl}/events': getDeploymentEvents,
  'GET /v13/deployments/{idOrUrl}': getDeployment,
  'POST /v13/deployments': createDeployment,
  'PATCH /v12/deployments/{id}/cancel': cancelDeployment,
  'POST /v4/domains/buy': buyDomain,
  'GET /v4/domains/price': checkDomainPrice,
  'GET /v4/domains/{domain}/records': getRecords,
  'POST /v2/domains/{domain}/records': createRecord,
  'PATCH /v1/domains/records/{recordId}': updateRecord,
  'DELETE /v2/domains/{domain}/records/{recordId}': removeRecord,
  'GET /v4/domains/status': checkDomainStatus,
  'GET /v1/domains/{domain}/registry': getDomainTransfer,
  'GET /v6/domains/{domain}/config': getDomainConfig,
  'GET /v5/domains/{domain}': getDomain,
  'GET /v5/domains': getDomains,
  'POST /v5/domains': createOrTransferDomain,
  'PATCH /v3/domains/{domain}': patchDomain,
  'DELETE /v6/domains/{domain}': deleteDomain,
  'GET /v1/edge-config': getEdgeConfigs,
  'POST /v1/edge-config': createEdgeConfig,
  'GET /v1/edge-config/{edgeConfigId}': getEdgeConfig,
  'PUT /v1/edge-config/{edgeConfigId}': updateEdgeConfig,
  'DELETE /v1/edge-config/{edgeConfigId}': deleteEdgeConfig,
  'GET /v1/edge-config/{edgeConfigId}/items': getEdgeConfigItems,
  'PATCH /v1/edge-config/{edgeConfigId}/items': patchtEdgeConfigItems,
  'GET /v1/edge-config/{edgeConfigId}/item/{edgeConfigItemKey}': getEdgeConfigItem,
  'GET /v1/edge-config/{edgeConfigId}/tokens': getEdgeConfigTokens,
  'DELETE /v1/edge-config/{edgeConfigId}/tokens': deleteEdgeConfigTokens,
  'GET /v1/edge-config/{edgeConfigId}/token/{token}': getEdgeConfigToken,
  'POST /v1/edge-config/{edgeConfigId}/token': createEdgeConfigToken,
  'GET /v3/events': listUserEvents,
  'GET /v1/integrations/configurations': getConfigurations,
  'GET /v1/integrations/configuration/{id}': getConfiguration,
  'DELETE /v1/integrations/configuration/{id}': deleteConfiguration,
  'GET /v2/integrations/log-drains': getIntegrationLogDrains,
  'POST /v2/integrations/log-drains': createLogDrain,
  'DELETE /v1/integrations/log-drains/{id}': deleteIntegrationLogDrain,
  'GET /v1/integrations/git-namespaces': gitNamespaces,
  'GET /v1/integrations/search-repo': searchRepo,
  'GET /v1/log-drains/{id}': getConfigurableLogDrain,
  'DELETE /v1/log-drains/{id}': deleteConfigurableLogDrain,
  'GET /v1/log-drains': getConfigurableLogDrains,
  'POST /v1/log-drains': createConfigurableLogDrain,
  'GET /v1/projects/{idOrName}/members': getProjectMembers,
  'POST /v1/projects/{idOrName}/members': addProjectMember,
  'DELETE /v1/projects/{idOrName}/members/{uid}': removeProjectMember,
  'GET /v9/projects': getProjects,
  'POST /v9/projects': createProject,
  'GET /v9/projects/{idOrName}': getProject,
  'PATCH /v9/projects/{idOrName}': updateProject,
  'DELETE /v9/projects/{idOrName}': deleteProject,
  'GET /v9/projects/{idOrName}/domains': getProjectDomains,
  'GET /v9/projects/{idOrName}/domains/{domain}': getProjectDomain,
  'PATCH /v9/projects/{idOrName}/domains/{domain}': updateProjectDomain,
  'DELETE /v9/projects/{idOrName}/domains/{domain}': removeProjectDomain,
  'POST /v10/projects/{idOrName}/domains': addProjectDomain,
  'POST /v9/projects/{idOrName}/domains/{domain}/verify': verifyProjectDomain,
  'GET /v9/projects/{idOrName}/env': filterProjectEnvs,
  'GET /v1/projects/{idOrName}/env/{id}': getProjectEnv,
  'POST /v10/projects/{idOrName}/env': createProjectEnv,
  'DELETE /v9/projects/{idOrName}/env/{id}': removeProjectEnv,
  'PATCH /v9/projects/{idOrName}/env/{id}': editProjectEnv,
  'GET /v2/teams/{teamId}/members': getTeamMembers,
  'POST /v1/teams/{teamId}/members': inviteUserToTeam,
  'POST /v1/teams/{teamId}/request': requestAccessToTeam,
  'GET /v1/teams/{teamId}/request/{userId}': getTeamAccessRequest,
  'POST /v1/teams/{teamId}/members/teams/join': joinTeam,
  'PATCH /v1/teams/{teamId}/members/{uid}': updateTeamMember,
  'DELETE /v1/teams/{teamId}/members/{uid}': removeTeamMember,
  'GET /v2/teams/{teamId}': getTeam,
  'PATCH /v2/teams/{teamId}': patchTeam,
  'GET /v2/teams': getTeams,
  'POST /v1/teams': createTeam,
  'DELETE /v1/teams/{teamId}': deleteTeam,
  'DELETE /v1/teams/{teamId}/invites/{inviteId}': deleteTeamInviteCode,
  'POST /v2/files': uploadFile,
  'GET /v2/user': getAuthUser,
  'DELETE /v1/user': requestDelete,
  'GET /v5/user/tokens': listAuthTokens,
  'POST /v3/user/tokens': createAuthToken,
  'GET /v5/user/tokens/{tokenId}': getAuthToken,
  'DELETE /v3/user/tokens/{tokenId}': deleteAuthToken,
  'POST /v1/webhooks': createWebhook,
  'GET /v1/webhooks': getWebhooks,
  'GET /v1/webhooks/{id}': getWebhook,
  'DELETE /v1/webhooks/{id}': deleteWebhook,
  'GET /v4/aliases': listAliases,
  'GET /v4/aliases/{idOrAlias}': getAlias,
  'DELETE /v2/aliases/{aliasId}': deleteAlias,
  'GET /v2/deployments/{id}/aliases': listDeploymentAliases,
  'POST /v2/deployments/{id}/aliases': assignAlias,
  'GET /v7/certs/{id}': getCertById,
  'DELETE /v7/certs/{id}': removeCert,
  'POST /v7/certs': issueCert,
  'PUT /v7/certs': uploadCert,
  'GET /v6/deployments/{id}/files': listDeploymentFiles,
  'GET /v6/deployments/{id}/files/{fileId}': getDeploymentFileContents,
  'GET /v6/deployments': getDeployments,
  'GET /registration/verify': verifyToken,
  'POST /registration': emailLogin,
  'DELETE /v13/deployments/{id}': deleteDeployment,
  'GET /v3/secrets': getSecrets,
  'POST /v2/secrets/{name}': createSecret,
  'PATCH /v2/secrets/{name}': renameSecret,
  'GET /v3/secrets/{idOrName}': getSecret,
  'DELETE /v2/secrets/{idOrName}': deleteSecret
};
