/**
 * Generated by @openapi-codegen
 *
 * @version 4.0.0
 */
import type * as Schemas from "./schemas";

/**
 * Page number of results.
 *
 * @default 1
 */
export type AccessPage = number;

/**
 * Number of results per page.
 *
 * @default 1000
 */
export type AccessPerPage = number;

export type ApiShieldApiDiscoveryOriginParameter =
  Schemas.ApiShieldApiDiscoveryOrigin;

export type ApiShieldApiDiscoveryStateParameter =
  Schemas.ApiShieldApiDiscoveryState;

export type ApiShieldConfigId = Schemas.ApiShieldSchemasUuid;

/**
 * When `true`, only return API Discovery results that are not saved into API Shield Endpoint Management
 */
export type ApiShieldDiffParameter = boolean;

/**
 * Direction to order results.
 *
 * @example desc
 */
export type ApiShieldDirectionParameter = "asc" | "desc";

/**
 * Filter results to only include endpoints containing this pattern.
 *
 * @example /api/v1
 */
export type ApiShieldEndpointParameter = string;

/**
 * Filter results to only include the specified hosts.
 *
 * @uniqueItems true
 */
export type ApiShieldHostParameter = string[];

/**
 * Filter results to only include the specified HTTP methods.
 *
 * @uniqueItems true
 */
export type ApiShieldMethodParameter = string[];

/**
 * @default false
 */
export type ApiShieldOldOmitSource = boolean;

/**
 * @format uuid
 * @maxLength 36
 */
export type ApiShieldOldSchemaId = string;

/**
 * @default false
 */
export type ApiShieldOmitSourceQuery = boolean;

/**
 * @example thresholds
 * @uniqueItems true
 */
export type ApiShieldOperationFeatureParameter = (
  | "thresholds"
  | "parameter_schemas"
  | "schema_info"
)[];

export type ApiShieldOperationId = Schemas.ApiShieldUuid;

/**
 * Field to order by
 *
 * @example method
 */
export type ApiShieldOrderParameter =
  | "host"
  | "method"
  | "endpoint"
  | "traffic_stats.requests"
  | "traffic_stats.last_updated";

/**
 * @default 1
 * @minimum 1
 */
export type ApiShieldPage = number;

export type ApiShieldParametersOperationId = Schemas.ApiShieldSchemasUuid;

/**
 * @default 20
 * @maximum 50
 * @minimum 5
 */
export type ApiShieldPerPage = number;

export type ApiShieldRuleId = Schemas.ApiShieldSchemasUuid;

/**
 * @format uuid
 */
export type ApiShieldSchemaIdPath = Schemas.ApiShieldSchemasUuid & string;

export type ApiShieldZoneId = Schemas.ApiShieldSchemasIdentifier;

/**
 * @example account-123
 */
export type BuildsAccountId = string;

/**
 * @format uuid
 */
export type BuildsBuildUuid = string;

/**
 * @default 1
 * @minimum 1
 */
export type BuildsPage = number;

/**
 * @default 50
 * @maximum 200
 * @minimum 1
 */
export type BuildsPerPage = number;

/**
 * @format uuid
 */
export type BuildsRepoConnectionUuid = string;

/**
 * @format uuid
 */
export type BuildsTriggerUuid = string;

export type DlsAccountId = Schemas.DlsIdentifier;

export type DlsHostname = Schemas.DlsHostname;

export type DlsZoneId = Schemas.DlsIdentifier;

/**
 * @default 1
 * @minimum 1
 */
export type HealthchecksPage = number;

/**
 * @default 25
 * @maximum 1000
 * @minimum 5
 */
export type HealthchecksPerPage = number;

export type OrganizationsApiOrganizationListFiltersContainingAccount = string;

export type OrganizationsApiOrganizationListFiltersContainingOrganization =
  string;

export type OrganizationsApiOrganizationListFiltersContainingUser = string;

export type OrganizationsApiOrganizationListFiltersId =
  Schemas.OrganizationsApiOrganizationID[];

export type OrganizationsApiOrganizationListFiltersName = string;

export type OrganizationsApiOrganizationListFiltersNameContains = string;

export type OrganizationsApiOrganizationListFiltersNameEndsWith = string;

export type OrganizationsApiOrganizationListFiltersNameStartsWith = string;

export type OrganizationsApiOrganizationListFiltersParentId =
  | Schemas.OrganizationsApiOrganizationID
  | "null";

/**
 * @maximum 1000
 * @minimum 0
 */
export type OrganizationsApiPageTokenParamsPageSize = number;

export type OrganizationsApiPageTokenParamsPageToken = string;

export type RealtimekitAccountId = Schemas.RealtimekitAccountIdentifier;

export type RealtimekitAppId = Schemas.RealtimekitAppId;

/**
 * @example 2022-09-22
 */
export type RealtimekitEndDate = string;

/**
 * @format date-time
 */
export type RealtimekitEndTime = string;

export type RealtimekitMeetingId = string;

/**
 * @pattern ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
 */
export type RealtimekitMeetingId = string;

/**
 * @minimum 0
 */
export type RealtimekitPageNo = number;

export type RealtimekitParticipantId = string;

/**
 * @example 1:10
 */
export type RealtimekitParticipants = string;

export type RealtimekitParticipantsSortBy = "joinedAt" | "duration";

/**
 * @minimum 0
 */
export type RealtimekitPerPage = number;

export type RealtimekitRecordingSortBy = "invokedTime";

export type RealtimekitRecordingStatus = (
  | "INVOKED"
  | "RECORDING"
  | "UPLOADING"
  | "UPLOADED"
)[];

export type RealtimekitSearch = string;

export type RealtimekitSessionId = string;

export type RealtimekitSortBy = "minutesConsumed" | "createdAt";

export type RealtimekitSortOrder = "ASC" | "DESC";

/**
 * @example 2022-09-01
 */
export type RealtimekitStartDate = string;

/**
 * @format date-time
 */
export type RealtimekitStartTime = string;

export type RealtimekitStatus = "LIVE" | "ENDED";

export type RealtimekitStreamId = number;

/**
 * @default asc
 */
export type ResourceSharingDirection = "asc" | "desc";

/**
 * @example true
 */
export type ResourceSharingIncludeRecipientCounts = boolean;

/**
 * @example true
 */
export type ResourceSharingIncludeResources = boolean;

export type ResourceSharingKind = Schemas.ResourceSharingShareKind;

/**
 * @default created
 */
export type ResourceSharingOrder = "name" | "created";

/**
 * @example 2
 * @minimum 0
 * @multipleOf 1
 */
export type ResourceSharingPage = number;

/**
 * @example 20
 * @maximum 100
 * @minimum 0
 * @multipleOf 1
 */
export type ResourceSharingPerPage = number;

export type ResourceSharingResourceStatus =
  Schemas.ResourceSharingResourceStatus;

export type ResourceSharingResourceType = Schemas.ResourceSharingResourceType;

export type ResourceSharingResourceTypes =
  Schemas.ResourceSharingResourceType[];

export type ResourceSharingStatus = Schemas.ResourceSharingShareStatus;

export type ResourceSharingTargetType = Schemas.ResourceSharingShareTargetType;

/**
 * @default desc
 */
export type SecretsStoreDirection = "asc" | "desc";

/**
 * @default created
 */
export type SecretsStoreOrder =
  | "name"
  | "comment"
  | "created"
  | "modified"
  | "status";

/**
 * @example 2
 * @minimum 0
 * @multipleOf 1
 */
export type SecretsStorePage = number;

/**
 * @example 20
 * @maximum 100
 * @minimum 0
 * @multipleOf 1
 */
export type SecretsStorePerPage = number;

export type SecretsStoreScopesQuery = Schemas.SecretsStoreScopes[];

export type SecretsStoreSearch = string;

/**
 * @default 1
 * @minimum 1
 */
export type SmartshieldPage = number;

/**
 * @default 25
 * @maximum 1000
 * @minimum 5
 */
export type SmartshieldPerPage = number;

export type TeamsDevicesDevicesGetDeviceParamInclude = string;

export type TeamsDevicesDevicesGetRegistrationParamInclude = string;

export type TeamsDevicesDevicesListDevicesParamActiveRegistrations =
  | "include"
  | "only"
  | "exclude";

export type TeamsDevicesDevicesListDevicesParamCursor = string;

export type TeamsDevicesDevicesListDevicesParamId = string[];

export type TeamsDevicesDevicesListDevicesParamInclude = string;

export type TeamsDevicesDevicesListDevicesParamLastSeenUserEmail = string;

/**
 * @format uint64
 */
export type TeamsDevicesDevicesListDevicesParamPerPage = number;

export type TeamsDevicesDevicesListDevicesParamSearch = string;

export type TeamsDevicesDevicesListDevicesParamSeenAfter = string;

export type TeamsDevicesDevicesListDevicesParamSeenBefore = string;

export type TeamsDevicesDevicesListDevicesParamSortBy =
  | "name"
  | "id"
  | "client_version"
  | "last_seen_user.email"
  | "last_seen_at"
  | "active_registrations"
  | "created_at";

export type TeamsDevicesDevicesListDevicesParamSortOrder = "asc" | "desc";

export type TeamsDevicesDevicesListRegistrationsParamCursor = string;

export type TeamsDevicesDevicesListRegistrationsParamDeviceId = string;

export type TeamsDevicesDevicesListRegistrationsParamId = string[];

export type TeamsDevicesDevicesListRegistrationsParamInclude = string;

/**
 * @format uint64
 */
export type TeamsDevicesDevicesListRegistrationsParamPerPage = number;

export type TeamsDevicesDevicesListRegistrationsParamSearch = string;

export type TeamsDevicesDevicesListRegistrationsParamSeenAfter = string;

export type TeamsDevicesDevicesListRegistrationsParamSeenBefore = string;

export type TeamsDevicesDevicesListRegistrationsParamSortBy =
  | "id"
  | "user.name"
  | "user.email"
  | "last_seen_at"
  | "created_at";

export type TeamsDevicesDevicesListRegistrationsParamSortOrder = "asc" | "desc";

export type TeamsDevicesDevicesListRegistrationsParamStatus =
  | "active"
  | "all"
  | "revoked";

export type TeamsDevicesDevicesListRegistrationsParamUserId = string[];

/**
 * @default 1
 * @minimum 1
 */
export type WaitingroomPage = number;

/**
 * @default 25
 * @maximum 1000
 * @minimum 5
 */
export type WaitingroomPerPage = number;
