import {
  buildLinkingUri,
  createConsent,
  deleteConsent,
  deleteCredential,
  deleteCurrentSession,
  deleteLinkedProvider,
  deleteSession,
  getAccount,
  getApplications,
  getConsent,
  getCredentials,
  getDevices,
  getGroups,
  getLinkedAccounts,
  getOrganizations,
  getSessions,
  updateAccount,
  updateConsent,
  updateCredentialLabel
} from './components';

export const operationsByPath = {
  'GET /account/': getAccount,
  'POST /account/': updateAccount,
  'GET /account/applications': getApplications,
  'GET /account/applications/{clientId}/consent': getConsent,
  'POST /account/applications/{clientId}/consent': createConsent,
  'PUT /account/applications/{clientId}/consent': updateConsent,
  'DELETE /account/applications/{clientId}/consent': deleteConsent,
  'GET /account/credentials': getCredentials,
  'DELETE /account/credentials/{credentialId}': deleteCredential,
  'PUT /account/credentials/{credentialId}/label': updateCredentialLabel,
  'GET /account/sessions': getSessions,
  'DELETE /account/sessions': deleteCurrentSession,
  'GET /account/sessions/devices': getDevices,
  'DELETE /account/sessions/{sessionId}': deleteSession,
  'GET /account/linked-accounts': getLinkedAccounts,
  'GET /account/linked-accounts/{providerId}': buildLinkingUri,
  'DELETE /account/linked-accounts/{providerId}': deleteLinkedProvider,
  'GET /account/groups': getGroups,
  'GET /account/organizations': getOrganizations
};
