import {
  listArchivedFiles,
  getArchivedFileStatistics,
  updateArchivedFile,
  getArchivedFiles,
  deleteArchivedFiles,
  recordingGet,
  recordingDelete,
  analyticsDetails,
  analyticsSummary,
  meetingRecordingRegistrants,
  meetingRecordingRegistrantCreate,
  recordingRegistrantsQuestionsGet,
  recordingRegistrantQuestionUpdate,
  meetingRecordingRegistrantStatus,
  recordingSettingUpdate,
  recordingSettingsUpdate,
  recordingDeleteOne,
  recordingStatusUpdateOne,
  recordingStatusUpdate,
  recordingsList,
  listDevices,
  addDevice,
  getzdmgroupinfo,
  assigndevicetoauserCommonarea,
  upgradeZpasApp,
  deleteZpaDeviceByVendorAndMacAddress,
  getZpaVersioninfo,
  getDevice,
  deleteDevice,
  updateDevice,
  changeDeviceAssociation,
  deviceList,
  deviceCreate,
  deviceDelete,
  deviceUpdate,
  deleteMeetingChatMessageById,
  updateMeetingChatMessageById,
  inMeetingControl,
  listmeetingsummaries,
  meeting,
  meetingDelete,
  meetingUpdate,
  createBatchPolls,
  addBatchRegistrants,
  meetingInvitation,
  meetingInviteLinksCreate,
  meetingLiveStreamingJoinToken,
  meetingLocalArchivingArchiveToken,
  meetingLocalRecordingJoinToken,
  getMeetingLiveStreamDetails,
  meetingLiveStreamUpdate,
  meetingLiveStreamStatusUpdate,
  getameetingsummary,
  meetingAppAdd,
  meetingAppDelete,
  meetingPolls,
  meetingPollCreate,
  meetingPollGet,
  meetingPollUpdate,
  meetingPollDelete,
  meetingRegistrants,
  meetingRegistrantCreate,
  meetingRegistrantsQuestionsGet,
  meetingRegistrantQuestionUpdate,
  meetingRegistrantStatus,
  meetingRegistrantGet,
  meetingregistrantdelete,
  getSipDialingWithPasscode,
  meetingStatus,
  meetingSurveyGet,
  meetingSurveyDelete,
  meetingSurveyUpdate,
  meetingToken,
  pastMeetingDetails,
  pastMeetings,
  pastMeetingParticipants,
  listPastMeetingPolls,
  listPastMeetingQA,
  listMeetingTemplates,
  meetingTemplateCreate,
  meetings,
  meetingCreate,
  listUpcomingMeeting,
  userPACs,
  reportSignInSignOutActivities,
  getBillingReport,
  getBillingInvoicesReports,
  reportCloudRecording,
  reportDaily,
  reportMeetingactivitylogs,
  reportMeetingDetails,
  reportMeetingParticipants,
  reportMeetingPolls,
  reportMeetingQA,
  reportMeetingSurvey,
  reportOperationLogs,
  reportTelephone,
  reportUpcomingEvents,
  reportUsers,
  reportMeetings,
  reportWebinarDetails,
  reportWebinarParticipants,
  reportWebinarPolls,
  reportWebinarQA,
  reportWebinarSurvey,
  listSipPhones,
  createSIPPhone,
  deleteSIPPhone,
  updateSIPPhone,
  tsp,
  tspUpdate,
  userTSPs,
  userTSPCreate,
  tspUrlUpdate,
  userTSP,
  userTSPDelete,
  userTSPUpdate,
  trackingfieldList,
  trackingfieldCreate,
  trackingfieldGet,
  trackingfieldDelete,
  trackingfieldUpdate,
  deleteWebinarChatMessageById,
  webinarAbsentees,
  pastWebinars,
  listWebinarParticipants,
  listPastWebinarPollResults,
  listPastWebinarQA,
  listWebinarTemplates,
  webinarTemplateCreate,
  webinars,
  webinarCreate,
  webinar,
  webinarDelete,
  webinarUpdate,
  addBatchWebinarRegistrants,
  getWebinarBranding,
  createWebinarBrandingNameTag,
  deleteWebinarBrandingNameTag,
  updateWebinarBrandingNameTag,
  uploadWebinarBrandingVB,
  deleteWebinarBrandingVB,
  setWebinarBrandingVB,
  uploadWebinarBrandingWallpaper,
  deleteWebinarBrandingWallpaper,
  webinarInviteLinksCreate,
  webinarLiveStreamingJoinToken,
  webinarLocalArchivingArchiveToken,
  webinarLocalRecordingJoinToken,
  getWebinarLiveStreamDetails,
  webinarLiveStreamUpdate,
  webinarLiveStreamStatusUpdate,
  webinarPanelists,
  webinarPanelistCreate,
  webinarPanelistsDelete,
  webinarPanelistDelete,
  webinarPolls,
  webinarPollCreate,
  webinarPollGet,
  webinarPollUpdate,
  webinarPollDelete,
  webinarRegistrants,
  webinarRegistrantCreate,
  webinarRegistrantsQuestionsGet,
  webinarRegistrantQuestionUpdate,
  webinarRegistrantStatus,
  webinarRegistrantGet,
  deleteWebinarRegistrant,
  getWebinarSipDialingWithPasscode,
  webinarStatus,
  webinarSurveyGet,
  webinarSurveyDelete,
  webinarSurveyUpdate,
  webinarToken,
  getTrackingSources
} from './components';

export const operationsByPath = {
  'GET /archive_files': listArchivedFiles,
  'GET /archive_files/statistics': getArchivedFileStatistics,
  'PATCH /archive_files/{fileId}': updateArchivedFile,
  'GET /past_meetings/{meetingUUID}/archive_files': getArchivedFiles,
  'DELETE /past_meetings/{meetingUUID}/archive_files': deleteArchivedFiles,
  'GET /meetings/{meetingId}/recordings': recordingGet,
  'DELETE /meetings/{meetingId}/recordings': recordingDelete,
  'GET /meetings/{meetingId}/recordings/analytics_details': analyticsDetails,
  'GET /meetings/{meetingId}/recordings/analytics_summary': analyticsSummary,
  'GET /meetings/{meetingId}/recordings/registrants': meetingRecordingRegistrants,
  'POST /meetings/{meetingId}/recordings/registrants': meetingRecordingRegistrantCreate,
  'GET /meetings/{meetingId}/recordings/registrants/questions': recordingRegistrantsQuestionsGet,
  'PATCH /meetings/{meetingId}/recordings/registrants/questions': recordingRegistrantQuestionUpdate,
  'PUT /meetings/{meetingId}/recordings/registrants/status': meetingRecordingRegistrantStatus,
  'GET /meetings/{meetingId}/recordings/settings': recordingSettingUpdate,
  'PATCH /meetings/{meetingId}/recordings/settings': recordingSettingsUpdate,
  'DELETE /meetings/{meetingId}/recordings/{recordingId}': recordingDeleteOne,
  'PUT /meetings/{meetingId}/recordings/{recordingId}/status': recordingStatusUpdateOne,
  'PUT /meetings/{meetingUUID}/recordings/status': recordingStatusUpdate,
  'GET /users/{userId}/recordings': recordingsList,
  'GET /devices': listDevices,
  'POST /devices': addDevice,
  'GET /devices/groups': getzdmgroupinfo,
  'POST /devices/zpa/assignment': assigndevicetoauserCommonarea,
  'POST /devices/zpa/upgrade': upgradeZpasApp,
  'DELETE /devices/zpa/vendors/{vendor}/mac_addresses/{macAddress}': deleteZpaDeviceByVendorAndMacAddress,
  'GET /devices/zpa/zdm_groups/{zdmGroupId}/versions': getZpaVersioninfo,
  'GET /devices/{deviceId}': getDevice,
  'DELETE /devices/{deviceId}': deleteDevice,
  'PATCH /devices/{deviceId}': updateDevice,
  'PATCH /devices/{deviceId}/assignment': changeDeviceAssociation,
  'GET /h323/devices': deviceList,
  'POST /h323/devices': deviceCreate,
  'DELETE /h323/devices/{deviceId}': deviceDelete,
  'PATCH /h323/devices/{deviceId}': deviceUpdate,
  'DELETE /live_meetings/{meetingId}/chat/messages/{messageId}': deleteMeetingChatMessageById,
  'PATCH /live_meetings/{meetingId}/chat/messages/{messageId}': updateMeetingChatMessageById,
  'PATCH /live_meetings/{meetingId}/events': inMeetingControl,
  'GET /meetings/meeting_summaries': listmeetingsummaries,
  'GET /meetings/{meetingId}': meeting,
  'DELETE /meetings/{meetingId}': meetingDelete,
  'PATCH /meetings/{meetingId}': meetingUpdate,
  'POST /meetings/{meetingId}/batch_polls': createBatchPolls,
  'POST /meetings/{meetingId}/batch_registrants': addBatchRegistrants,
  'GET /meetings/{meetingId}/invitation': meetingInvitation,
  'POST /meetings/{meetingId}/invite_links': meetingInviteLinksCreate,
  'GET /meetings/{meetingId}/jointoken/live_streaming': meetingLiveStreamingJoinToken,
  'GET /meetings/{meetingId}/jointoken/local_archiving': meetingLocalArchivingArchiveToken,
  'GET /meetings/{meetingId}/jointoken/local_recording': meetingLocalRecordingJoinToken,
  'GET /meetings/{meetingId}/livestream': getMeetingLiveStreamDetails,
  'PATCH /meetings/{meetingId}/livestream': meetingLiveStreamUpdate,
  'PATCH /meetings/{meetingId}/livestream/status': meetingLiveStreamStatusUpdate,
  'GET /meetings/{meetingId}/meeting_summary': getameetingsummary,
  'POST /meetings/{meetingId}/open_apps': meetingAppAdd,
  'DELETE /meetings/{meetingId}/open_apps': meetingAppDelete,
  'GET /meetings/{meetingId}/polls': meetingPolls,
  'POST /meetings/{meetingId}/polls': meetingPollCreate,
  'GET /meetings/{meetingId}/polls/{pollId}': meetingPollGet,
  'PUT /meetings/{meetingId}/polls/{pollId}': meetingPollUpdate,
  'DELETE /meetings/{meetingId}/polls/{pollId}': meetingPollDelete,
  'GET /meetings/{meetingId}/registrants': meetingRegistrants,
  'POST /meetings/{meetingId}/registrants': meetingRegistrantCreate,
  'GET /meetings/{meetingId}/registrants/questions': meetingRegistrantsQuestionsGet,
  'PATCH /meetings/{meetingId}/registrants/questions': meetingRegistrantQuestionUpdate,
  'PUT /meetings/{meetingId}/registrants/status': meetingRegistrantStatus,
  'GET /meetings/{meetingId}/registrants/{registrantId}': meetingRegistrantGet,
  'DELETE /meetings/{meetingId}/registrants/{registrantId}': meetingregistrantdelete,
  'POST /meetings/{meetingId}/sip_dialing': getSipDialingWithPasscode,
  'PUT /meetings/{meetingId}/status': meetingStatus,
  'GET /meetings/{meetingId}/survey': meetingSurveyGet,
  'DELETE /meetings/{meetingId}/survey': meetingSurveyDelete,
  'PATCH /meetings/{meetingId}/survey': meetingSurveyUpdate,
  'GET /meetings/{meetingId}/token': meetingToken,
  'GET /past_meetings/{meetingId}': pastMeetingDetails,
  'GET /past_meetings/{meetingId}/instances': pastMeetings,
  'GET /past_meetings/{meetingId}/participants': pastMeetingParticipants,
  'GET /past_meetings/{meetingId}/polls': listPastMeetingPolls,
  'GET /past_meetings/{meetingId}/qa': listPastMeetingQA,
  'GET /users/{userId}/meeting_templates': listMeetingTemplates,
  'POST /users/{userId}/meeting_templates': meetingTemplateCreate,
  'GET /users/{userId}/meetings': meetings,
  'POST /users/{userId}/meetings': meetingCreate,
  'GET /users/{userId}/upcoming_meetings': listUpcomingMeeting,
  'GET /users/{userId}/pac': userPACs,
  'GET /report/activities': reportSignInSignOutActivities,
  'GET /report/billing': getBillingReport,
  'GET /report/billing/invoices': getBillingInvoicesReports,
  'GET /report/cloud_recording': reportCloudRecording,
  'GET /report/daily': reportDaily,
  'GET /report/meeting_activities': reportMeetingactivitylogs,
  'GET /report/meetings/{meetingId}': reportMeetingDetails,
  'GET /report/meetings/{meetingId}/participants': reportMeetingParticipants,
  'GET /report/meetings/{meetingId}/polls': reportMeetingPolls,
  'GET /report/meetings/{meetingId}/qa': reportMeetingQA,
  'GET /report/meetings/{meetingId}/survey': reportMeetingSurvey,
  'GET /report/operationlogs': reportOperationLogs,
  'GET /report/telephone': reportTelephone,
  'GET /report/upcoming_events': reportUpcomingEvents,
  'GET /report/users': reportUsers,
  'GET /report/users/{userId}/meetings': reportMeetings,
  'GET /report/webinars/{webinarId}': reportWebinarDetails,
  'GET /report/webinars/{webinarId}/participants': reportWebinarParticipants,
  'GET /report/webinars/{webinarId}/polls': reportWebinarPolls,
  'GET /report/webinars/{webinarId}/qa': reportWebinarQA,
  'GET /report/webinars/{webinarId}/survey': reportWebinarSurvey,
  'GET /sip_phones': listSipPhones,
  'POST /sip_phones': createSIPPhone,
  'DELETE /sip_phones/{phoneId}': deleteSIPPhone,
  'PATCH /sip_phones/{phoneId}': updateSIPPhone,
  'GET /tsp': tsp,
  'PATCH /tsp': tspUpdate,
  'GET /users/{userId}/tsp': userTSPs,
  'POST /users/{userId}/tsp': userTSPCreate,
  'PATCH /users/{userId}/tsp/settings': tspUrlUpdate,
  'GET /users/{userId}/tsp/{tspId}': userTSP,
  'DELETE /users/{userId}/tsp/{tspId}': userTSPDelete,
  'PATCH /users/{userId}/tsp/{tspId}': userTSPUpdate,
  'GET /tracking_fields': trackingfieldList,
  'POST /tracking_fields': trackingfieldCreate,
  'GET /tracking_fields/{fieldId}': trackingfieldGet,
  'DELETE /tracking_fields/{fieldId}': trackingfieldDelete,
  'PATCH /tracking_fields/{fieldId}': trackingfieldUpdate,
  'DELETE /live_webinars/{webinarId}/chat/messages/{messageId}': deleteWebinarChatMessageById,
  'GET /past_webinars/{webinarId}/absentees': webinarAbsentees,
  'GET /past_webinars/{webinarId}/instances': pastWebinars,
  'GET /past_webinars/{webinarId}/participants': listWebinarParticipants,
  'GET /past_webinars/{webinarId}/polls': listPastWebinarPollResults,
  'GET /past_webinars/{webinarId}/qa': listPastWebinarQA,
  'GET /users/{userId}/webinar_templates': listWebinarTemplates,
  'POST /users/{userId}/webinar_templates': webinarTemplateCreate,
  'GET /users/{userId}/webinars': webinars,
  'POST /users/{userId}/webinars': webinarCreate,
  'GET /webinars/{webinarId}': webinar,
  'DELETE /webinars/{webinarId}': webinarDelete,
  'PATCH /webinars/{webinarId}': webinarUpdate,
  'POST /webinars/{webinarId}/batch_registrants': addBatchWebinarRegistrants,
  'GET /webinars/{webinarId}/branding': getWebinarBranding,
  'POST /webinars/{webinarId}/branding/name_tags': createWebinarBrandingNameTag,
  'DELETE /webinars/{webinarId}/branding/name_tags': deleteWebinarBrandingNameTag,
  'PATCH /webinars/{webinarId}/branding/name_tags/{nameTagId}': updateWebinarBrandingNameTag,
  'POST /webinars/{webinarId}/branding/virtual_backgrounds': uploadWebinarBrandingVB,
  'DELETE /webinars/{webinarId}/branding/virtual_backgrounds': deleteWebinarBrandingVB,
  'PATCH /webinars/{webinarId}/branding/virtual_backgrounds': setWebinarBrandingVB,
  'POST /webinars/{webinarId}/branding/wallpaper': uploadWebinarBrandingWallpaper,
  'DELETE /webinars/{webinarId}/branding/wallpaper': deleteWebinarBrandingWallpaper,
  'POST /webinars/{webinarId}/invite_links': webinarInviteLinksCreate,
  'GET /webinars/{webinarId}/jointoken/live_streaming': webinarLiveStreamingJoinToken,
  'GET /webinars/{webinarId}/jointoken/local_archiving': webinarLocalArchivingArchiveToken,
  'GET /webinars/{webinarId}/jointoken/local_recording': webinarLocalRecordingJoinToken,
  'GET /webinars/{webinarId}/livestream': getWebinarLiveStreamDetails,
  'PATCH /webinars/{webinarId}/livestream': webinarLiveStreamUpdate,
  'PATCH /webinars/{webinarId}/livestream/status': webinarLiveStreamStatusUpdate,
  'GET /webinars/{webinarId}/panelists': webinarPanelists,
  'POST /webinars/{webinarId}/panelists': webinarPanelistCreate,
  'DELETE /webinars/{webinarId}/panelists': webinarPanelistsDelete,
  'DELETE /webinars/{webinarId}/panelists/{panelistId}': webinarPanelistDelete,
  'GET /webinars/{webinarId}/polls': webinarPolls,
  'POST /webinars/{webinarId}/polls': webinarPollCreate,
  'GET /webinars/{webinarId}/polls/{pollId}': webinarPollGet,
  'PUT /webinars/{webinarId}/polls/{pollId}': webinarPollUpdate,
  'DELETE /webinars/{webinarId}/polls/{pollId}': webinarPollDelete,
  'GET /webinars/{webinarId}/registrants': webinarRegistrants,
  'POST /webinars/{webinarId}/registrants': webinarRegistrantCreate,
  'GET /webinars/{webinarId}/registrants/questions': webinarRegistrantsQuestionsGet,
  'PATCH /webinars/{webinarId}/registrants/questions': webinarRegistrantQuestionUpdate,
  'PUT /webinars/{webinarId}/registrants/status': webinarRegistrantStatus,
  'GET /webinars/{webinarId}/registrants/{registrantId}': webinarRegistrantGet,
  'DELETE /webinars/{webinarId}/registrants/{registrantId}': deleteWebinarRegistrant,
  'POST /webinars/{webinarId}/sip_dialing': getWebinarSipDialingWithPasscode,
  'PUT /webinars/{webinarId}/status': webinarStatus,
  'GET /webinars/{webinarId}/survey': webinarSurveyGet,
  'DELETE /webinars/{webinarId}/survey': webinarSurveyDelete,
  'PATCH /webinars/{webinarId}/survey': webinarSurveyUpdate,
  'GET /webinars/{webinarId}/token': webinarToken,
  'GET /webinars/{webinarId}/tracking_sources': getTrackingSources
};
