import {
  getArchiveFilesStatistics,
  patchArchiveFilesFileId,
  getArchiveFiles,
  getPastMeetingsMeetingUUIDArchiveFiles,
  deletePastMeetingsMeetingUUIDArchiveFiles,
  getPastMeetingsMeetingIdInstances,
  getPastMeetingsMeetingIdParticipants,
  getPastMeetingsMeetingIdPolls,
  getPastMeetingsMeetingIdQa,
  getPastMeetingsMeetingId,
  getDevicesGroups,
  postDevicesZpaAssignment,
  postDevicesZpaUpgrade,
  deleteDevicesZpaVendorsVendorMacAddressesMacAddress,
  getDevicesZpaZdmGroupsZdmGroupIdVersions,
  patchDevicesDeviceIdAssignment,
  getDevicesDeviceId,
  deleteDevicesDeviceId,
  patchDevicesDeviceId,
  getDevices,
  postDevices,
  getUsersUserIdRecordings,
  getUsersUserIdMeetingTemplates,
  postUsersUserIdMeetingTemplates,
  getUsersUserIdMeetings,
  postUsersUserIdMeetings,
  getUsersUserIdUpcomingMeetings,
  getUsersUserIdPac,
  patchUsersUserIdTspSettings,
  getUsersUserIdTspTspId,
  deleteUsersUserIdTspTspId,
  patchUsersUserIdTspTspId,
  getUsersUserIdTsp,
  postUsersUserIdTsp,
  getUsersUserIdWebinarTemplates,
  postUsersUserIdWebinarTemplates,
  getUsersUserIdWebinars,
  postUsersUserIdWebinars,
  getMeetingsMeetingIdRecordingsAnalyticsDetails,
  getMeetingsMeetingIdRecordingsAnalyticsSummary,
  getMeetingsMeetingIdRecordingsRegistrantsQuestions,
  patchMeetingsMeetingIdRecordingsRegistrantsQuestions,
  putMeetingsMeetingIdRecordingsRegistrantsStatus,
  getMeetingsMeetingIdRecordingsRegistrants,
  postMeetingsMeetingIdRecordingsRegistrants,
  getMeetingsMeetingIdRecordingsSettings,
  patchMeetingsMeetingIdRecordingsSettings,
  putMeetingsMeetingIdRecordingsRecordingIdStatus,
  deleteMeetingsMeetingIdRecordingsRecordingId,
  getMeetingsMeetingIdRecordings,
  deleteMeetingsMeetingIdRecordings,
  postMeetingsMeetingIdBatchPolls,
  postMeetingsMeetingIdBatchRegistrants,
  getMeetingsMeetingIdInvitation,
  postMeetingsMeetingIdInviteLinks,
  getMeetingsMeetingIdJointokenLiveStreaming,
  getMeetingsMeetingIdJointokenLocalArchiving,
  getMeetingsMeetingIdJointokenLocalRecording,
  patchMeetingsMeetingIdLivestreamStatus,
  getMeetingsMeetingIdLivestream,
  patchMeetingsMeetingIdLivestream,
  getMeetingsMeetingIdMeetingSummary,
  getMeetingsMeetingIdPollsPollId,
  putMeetingsMeetingIdPollsPollId,
  deleteMeetingsMeetingIdPollsPollId,
  getMeetingsMeetingIdPolls,
  postMeetingsMeetingIdPolls,
  getMeetingsMeetingIdRegistrantsQuestions,
  patchMeetingsMeetingIdRegistrantsQuestions,
  putMeetingsMeetingIdRegistrantsStatus,
  getMeetingsMeetingIdRegistrantsRegistrantId,
  deleteMeetingsMeetingIdRegistrantsRegistrantId,
  getMeetingsMeetingIdRegistrants,
  postMeetingsMeetingIdRegistrants,
  postMeetingsMeetingIdSipDialing,
  putMeetingsMeetingIdStatus,
  getMeetingsMeetingIdSurvey,
  deleteMeetingsMeetingIdSurvey,
  patchMeetingsMeetingIdSurvey,
  getMeetingsMeetingIdToken,
  getMeetingsMeetingId,
  deleteMeetingsMeetingId,
  patchMeetingsMeetingId,
  putMeetingsMeetingUUIDRecordingsStatus,
  getMeetingsMeetingSummaries,
  deleteLiveMeetingsMeetingIdChatMessagesMessageId,
  patchLiveMeetingsMeetingIdChatMessagesMessageId,
  patchLiveMeetingsMeetingIdEvents,
  getReportActivities,
  getReportBillingInvoices,
  getReportBilling,
  getReportCloudRecording,
  getReportDaily,
  getReportMeetingsMeetingIdParticipants,
  getReportMeetingsMeetingIdPolls,
  getReportMeetingsMeetingIdQa,
  getReportMeetingsMeetingIdSurvey,
  getReportMeetingsMeetingId,
  getReportOperationlogs,
  getReportTelephone,
  getReportUpcomingEvents,
  getReportUsersUserIdMeetings,
  getReportUsers,
  getReportWebinarsWebinarIdParticipants,
  getReportWebinarsWebinarIdPolls,
  getReportWebinarsWebinarIdQa,
  getReportWebinarsWebinarIdSurvey,
  getReportWebinarsWebinarId,
  deleteSipPhonesPhoneId,
  patchSipPhonesPhoneId,
  getSipPhones,
  postSipPhones,
  getTsp,
  patchTsp,
  getTrackingFieldsFieldId,
  deleteTrackingFieldsFieldId,
  patchTrackingFieldsFieldId,
  getTrackingFields,
  postTrackingFields,
  deleteLiveWebinarsWebinarIdChatMessagesMessageId,
  getPastWebinarsWebinarIdAbsentees,
  getPastWebinarsWebinarIdInstances,
  getPastWebinarsWebinarIdParticipants,
  getPastWebinarsWebinarIdPolls,
  getPastWebinarsWebinarIdQa,
  postWebinarsWebinarIdBatchRegistrants,
  patchWebinarsWebinarIdBrandingNameTagsNameTagId,
  postWebinarsWebinarIdBrandingNameTags,
  deleteWebinarsWebinarIdBrandingNameTags,
  postWebinarsWebinarIdBrandingVirtualBackgrounds,
  deleteWebinarsWebinarIdBrandingVirtualBackgrounds,
  patchWebinarsWebinarIdBrandingVirtualBackgrounds,
  postWebinarsWebinarIdBrandingWallpaper,
  deleteWebinarsWebinarIdBrandingWallpaper,
  getWebinarsWebinarIdBranding,
  postWebinarsWebinarIdInviteLinks,
  getWebinarsWebinarIdJointokenLiveStreaming,
  getWebinarsWebinarIdJointokenLocalArchiving,
  getWebinarsWebinarIdJointokenLocalRecording,
  patchWebinarsWebinarIdLivestreamStatus,
  getWebinarsWebinarIdLivestream,
  patchWebinarsWebinarIdLivestream,
  deleteWebinarsWebinarIdPanelistsPanelistId,
  getWebinarsWebinarIdPanelists,
  postWebinarsWebinarIdPanelists,
  deleteWebinarsWebinarIdPanelists,
  getWebinarsWebinarIdPollsPollId,
  putWebinarsWebinarIdPollsPollId,
  deleteWebinarsWebinarIdPollsPollId,
  getWebinarsWebinarIdPolls,
  postWebinarsWebinarIdPolls,
  getWebinarsWebinarIdRegistrantsQuestions,
  patchWebinarsWebinarIdRegistrantsQuestions,
  putWebinarsWebinarIdRegistrantsStatus,
  getWebinarsWebinarIdRegistrantsRegistrantId,
  deleteWebinarsWebinarIdRegistrantsRegistrantId,
  getWebinarsWebinarIdRegistrants,
  postWebinarsWebinarIdRegistrants,
  postWebinarsWebinarIdSipDialing,
  putWebinarsWebinarIdStatus,
  getWebinarsWebinarIdSurvey,
  deleteWebinarsWebinarIdSurvey,
  patchWebinarsWebinarIdSurvey,
  getWebinarsWebinarIdToken,
  getWebinarsWebinarIdTrackingSources,
  getWebinarsWebinarId,
  deleteWebinarsWebinarId,
  patchWebinarsWebinarId,
  deleteH323DevicesDeviceId,
  patchH323DevicesDeviceId,
  getH323Devices,
  postH323Devices
} from './components';

export const operationsByPath = {
  'GET /archive_files/statistics': getArchiveFilesStatistics,
  'PATCH /archive_files/{fileId}': patchArchiveFilesFileId,
  'GET /archive_files': getArchiveFiles,
  'GET /past_meetings/{meetingUUID}/archive_files': getPastMeetingsMeetingUUIDArchiveFiles,
  'DELETE /past_meetings/{meetingUUID}/archive_files': deletePastMeetingsMeetingUUIDArchiveFiles,
  'GET /past_meetings/{meetingId}/instances': getPastMeetingsMeetingIdInstances,
  'GET /past_meetings/{meetingId}/participants': getPastMeetingsMeetingIdParticipants,
  'GET /past_meetings/{meetingId}/polls': getPastMeetingsMeetingIdPolls,
  'GET /past_meetings/{meetingId}/qa': getPastMeetingsMeetingIdQa,
  'GET /past_meetings/{meetingId}': getPastMeetingsMeetingId,
  'GET /devices/groups': getDevicesGroups,
  'POST /devices/zpa/assignment': postDevicesZpaAssignment,
  'POST /devices/zpa/upgrade': postDevicesZpaUpgrade,
  'DELETE /devices/zpa/vendors/{vendor}/mac_addresses/{macAddress}':
    deleteDevicesZpaVendorsVendorMacAddressesMacAddress,
  'GET /devices/zpa/zdm_groups/{zdmGroupId}/versions': getDevicesZpaZdmGroupsZdmGroupIdVersions,
  'PATCH /devices/{deviceId}/assignment': patchDevicesDeviceIdAssignment,
  'GET /devices/{deviceId}': getDevicesDeviceId,
  'DELETE /devices/{deviceId}': deleteDevicesDeviceId,
  'PATCH /devices/{deviceId}': patchDevicesDeviceId,
  'GET /devices': getDevices,
  'POST /devices': postDevices,
  'GET /users/{userId}/recordings': getUsersUserIdRecordings,
  'GET /users/{userId}/meeting_templates': getUsersUserIdMeetingTemplates,
  'POST /users/{userId}/meeting_templates': postUsersUserIdMeetingTemplates,
  'GET /users/{userId}/meetings': getUsersUserIdMeetings,
  'POST /users/{userId}/meetings': postUsersUserIdMeetings,
  'GET /users/{userId}/upcoming_meetings': getUsersUserIdUpcomingMeetings,
  'GET /users/{userId}/pac': getUsersUserIdPac,
  'PATCH /users/{userId}/tsp/settings': patchUsersUserIdTspSettings,
  'GET /users/{userId}/tsp/{tspId}': getUsersUserIdTspTspId,
  'DELETE /users/{userId}/tsp/{tspId}': deleteUsersUserIdTspTspId,
  'PATCH /users/{userId}/tsp/{tspId}': patchUsersUserIdTspTspId,
  'GET /users/{userId}/tsp': getUsersUserIdTsp,
  'POST /users/{userId}/tsp': postUsersUserIdTsp,
  'GET /users/{userId}/webinar_templates': getUsersUserIdWebinarTemplates,
  'POST /users/{userId}/webinar_templates': postUsersUserIdWebinarTemplates,
  'GET /users/{userId}/webinars': getUsersUserIdWebinars,
  'POST /users/{userId}/webinars': postUsersUserIdWebinars,
  'GET /meetings/{meetingId}/recordings/analytics_details': getMeetingsMeetingIdRecordingsAnalyticsDetails,
  'GET /meetings/{meetingId}/recordings/analytics_summary': getMeetingsMeetingIdRecordingsAnalyticsSummary,
  'GET /meetings/{meetingId}/recordings/registrants/questions': getMeetingsMeetingIdRecordingsRegistrantsQuestions,
  'PATCH /meetings/{meetingId}/recordings/registrants/questions': patchMeetingsMeetingIdRecordingsRegistrantsQuestions,
  'PUT /meetings/{meetingId}/recordings/registrants/status': putMeetingsMeetingIdRecordingsRegistrantsStatus,
  'GET /meetings/{meetingId}/recordings/registrants': getMeetingsMeetingIdRecordingsRegistrants,
  'POST /meetings/{meetingId}/recordings/registrants': postMeetingsMeetingIdRecordingsRegistrants,
  'GET /meetings/{meetingId}/recordings/settings': getMeetingsMeetingIdRecordingsSettings,
  'PATCH /meetings/{meetingId}/recordings/settings': patchMeetingsMeetingIdRecordingsSettings,
  'PUT /meetings/{meetingId}/recordings/{recordingId}/status': putMeetingsMeetingIdRecordingsRecordingIdStatus,
  'DELETE /meetings/{meetingId}/recordings/{recordingId}': deleteMeetingsMeetingIdRecordingsRecordingId,
  'GET /meetings/{meetingId}/recordings': getMeetingsMeetingIdRecordings,
  'DELETE /meetings/{meetingId}/recordings': deleteMeetingsMeetingIdRecordings,
  'POST /meetings/{meetingId}/batch_polls': postMeetingsMeetingIdBatchPolls,
  'POST /meetings/{meetingId}/batch_registrants': postMeetingsMeetingIdBatchRegistrants,
  'GET /meetings/{meetingId}/invitation': getMeetingsMeetingIdInvitation,
  'POST /meetings/{meetingId}/invite_links': postMeetingsMeetingIdInviteLinks,
  'GET /meetings/{meetingId}/jointoken/live_streaming': getMeetingsMeetingIdJointokenLiveStreaming,
  'GET /meetings/{meetingId}/jointoken/local_archiving': getMeetingsMeetingIdJointokenLocalArchiving,
  'GET /meetings/{meetingId}/jointoken/local_recording': getMeetingsMeetingIdJointokenLocalRecording,
  'PATCH /meetings/{meetingId}/livestream/status': patchMeetingsMeetingIdLivestreamStatus,
  'GET /meetings/{meetingId}/livestream': getMeetingsMeetingIdLivestream,
  'PATCH /meetings/{meetingId}/livestream': patchMeetingsMeetingIdLivestream,
  'GET /meetings/{meetingId}/meeting_summary': getMeetingsMeetingIdMeetingSummary,
  'GET /meetings/{meetingId}/polls/{pollId}': getMeetingsMeetingIdPollsPollId,
  'PUT /meetings/{meetingId}/polls/{pollId}': putMeetingsMeetingIdPollsPollId,
  'DELETE /meetings/{meetingId}/polls/{pollId}': deleteMeetingsMeetingIdPollsPollId,
  'GET /meetings/{meetingId}/polls': getMeetingsMeetingIdPolls,
  'POST /meetings/{meetingId}/polls': postMeetingsMeetingIdPolls,
  'GET /meetings/{meetingId}/registrants/questions': getMeetingsMeetingIdRegistrantsQuestions,
  'PATCH /meetings/{meetingId}/registrants/questions': patchMeetingsMeetingIdRegistrantsQuestions,
  'PUT /meetings/{meetingId}/registrants/status': putMeetingsMeetingIdRegistrantsStatus,
  'GET /meetings/{meetingId}/registrants/{registrantId}': getMeetingsMeetingIdRegistrantsRegistrantId,
  'DELETE /meetings/{meetingId}/registrants/{registrantId}': deleteMeetingsMeetingIdRegistrantsRegistrantId,
  'GET /meetings/{meetingId}/registrants': getMeetingsMeetingIdRegistrants,
  'POST /meetings/{meetingId}/registrants': postMeetingsMeetingIdRegistrants,
  'POST /meetings/{meetingId}/sip_dialing': postMeetingsMeetingIdSipDialing,
  'PUT /meetings/{meetingId}/status': putMeetingsMeetingIdStatus,
  'GET /meetings/{meetingId}/survey': getMeetingsMeetingIdSurvey,
  'DELETE /meetings/{meetingId}/survey': deleteMeetingsMeetingIdSurvey,
  'PATCH /meetings/{meetingId}/survey': patchMeetingsMeetingIdSurvey,
  'GET /meetings/{meetingId}/token': getMeetingsMeetingIdToken,
  'GET /meetings/{meetingId}': getMeetingsMeetingId,
  'DELETE /meetings/{meetingId}': deleteMeetingsMeetingId,
  'PATCH /meetings/{meetingId}': patchMeetingsMeetingId,
  'PUT /meetings/{meetingUUID}/recordings/status': putMeetingsMeetingUUIDRecordingsStatus,
  'GET /meetings/meeting_summaries': getMeetingsMeetingSummaries,
  'DELETE /live_meetings/{meetingId}/chat/messages/{messageId}': deleteLiveMeetingsMeetingIdChatMessagesMessageId,
  'PATCH /live_meetings/{meetingId}/chat/messages/{messageId}': patchLiveMeetingsMeetingIdChatMessagesMessageId,
  'PATCH /live_meetings/{meetingId}/events': patchLiveMeetingsMeetingIdEvents,
  'GET /report/activities': getReportActivities,
  'GET /report/billing/invoices': getReportBillingInvoices,
  'GET /report/billing': getReportBilling,
  'GET /report/cloud_recording': getReportCloudRecording,
  'GET /report/daily': getReportDaily,
  'GET /report/meetings/{meetingId}/participants': getReportMeetingsMeetingIdParticipants,
  'GET /report/meetings/{meetingId}/polls': getReportMeetingsMeetingIdPolls,
  'GET /report/meetings/{meetingId}/qa': getReportMeetingsMeetingIdQa,
  'GET /report/meetings/{meetingId}/survey': getReportMeetingsMeetingIdSurvey,
  'GET /report/meetings/{meetingId}': getReportMeetingsMeetingId,
  'GET /report/operationlogs': getReportOperationlogs,
  'GET /report/telephone': getReportTelephone,
  'GET /report/upcoming_events': getReportUpcomingEvents,
  'GET /report/users/{userId}/meetings': getReportUsersUserIdMeetings,
  'GET /report/users': getReportUsers,
  'GET /report/webinars/{webinarId}/participants': getReportWebinarsWebinarIdParticipants,
  'GET /report/webinars/{webinarId}/polls': getReportWebinarsWebinarIdPolls,
  'GET /report/webinars/{webinarId}/qa': getReportWebinarsWebinarIdQa,
  'GET /report/webinars/{webinarId}/survey': getReportWebinarsWebinarIdSurvey,
  'GET /report/webinars/{webinarId}': getReportWebinarsWebinarId,
  'DELETE /sip_phones/{phoneId}': deleteSipPhonesPhoneId,
  'PATCH /sip_phones/{phoneId}': patchSipPhonesPhoneId,
  'GET /sip_phones': getSipPhones,
  'POST /sip_phones': postSipPhones,
  'GET /tsp': getTsp,
  'PATCH /tsp': patchTsp,
  'GET /tracking_fields/{fieldId}': getTrackingFieldsFieldId,
  'DELETE /tracking_fields/{fieldId}': deleteTrackingFieldsFieldId,
  'PATCH /tracking_fields/{fieldId}': patchTrackingFieldsFieldId,
  'GET /tracking_fields': getTrackingFields,
  'POST /tracking_fields': postTrackingFields,
  'DELETE /live_webinars/{webinarId}/chat/messages/{messageId}': deleteLiveWebinarsWebinarIdChatMessagesMessageId,
  'GET /past_webinars/{webinarId}/absentees': getPastWebinarsWebinarIdAbsentees,
  'GET /past_webinars/{webinarId}/instances': getPastWebinarsWebinarIdInstances,
  'GET /past_webinars/{webinarId}/participants': getPastWebinarsWebinarIdParticipants,
  'GET /past_webinars/{webinarId}/polls': getPastWebinarsWebinarIdPolls,
  'GET /past_webinars/{webinarId}/qa': getPastWebinarsWebinarIdQa,
  'POST /webinars/{webinarId}/batch_registrants': postWebinarsWebinarIdBatchRegistrants,
  'PATCH /webinars/{webinarId}/branding/name_tags/{nameTagId}': patchWebinarsWebinarIdBrandingNameTagsNameTagId,
  'POST /webinars/{webinarId}/branding/name_tags': postWebinarsWebinarIdBrandingNameTags,
  'DELETE /webinars/{webinarId}/branding/name_tags': deleteWebinarsWebinarIdBrandingNameTags,
  'POST /webinars/{webinarId}/branding/virtual_backgrounds': postWebinarsWebinarIdBrandingVirtualBackgrounds,
  'DELETE /webinars/{webinarId}/branding/virtual_backgrounds': deleteWebinarsWebinarIdBrandingVirtualBackgrounds,
  'PATCH /webinars/{webinarId}/branding/virtual_backgrounds': patchWebinarsWebinarIdBrandingVirtualBackgrounds,
  'POST /webinars/{webinarId}/branding/wallpaper': postWebinarsWebinarIdBrandingWallpaper,
  'DELETE /webinars/{webinarId}/branding/wallpaper': deleteWebinarsWebinarIdBrandingWallpaper,
  'GET /webinars/{webinarId}/branding': getWebinarsWebinarIdBranding,
  'POST /webinars/{webinarId}/invite_links': postWebinarsWebinarIdInviteLinks,
  'GET /webinars/{webinarId}/jointoken/live_streaming': getWebinarsWebinarIdJointokenLiveStreaming,
  'GET /webinars/{webinarId}/jointoken/local_archiving': getWebinarsWebinarIdJointokenLocalArchiving,
  'GET /webinars/{webinarId}/jointoken/local_recording': getWebinarsWebinarIdJointokenLocalRecording,
  'PATCH /webinars/{webinarId}/livestream/status': patchWebinarsWebinarIdLivestreamStatus,
  'GET /webinars/{webinarId}/livestream': getWebinarsWebinarIdLivestream,
  'PATCH /webinars/{webinarId}/livestream': patchWebinarsWebinarIdLivestream,
  'DELETE /webinars/{webinarId}/panelists/{panelistId}': deleteWebinarsWebinarIdPanelistsPanelistId,
  'GET /webinars/{webinarId}/panelists': getWebinarsWebinarIdPanelists,
  'POST /webinars/{webinarId}/panelists': postWebinarsWebinarIdPanelists,
  'DELETE /webinars/{webinarId}/panelists': deleteWebinarsWebinarIdPanelists,
  'GET /webinars/{webinarId}/polls/{pollId}': getWebinarsWebinarIdPollsPollId,
  'PUT /webinars/{webinarId}/polls/{pollId}': putWebinarsWebinarIdPollsPollId,
  'DELETE /webinars/{webinarId}/polls/{pollId}': deleteWebinarsWebinarIdPollsPollId,
  'GET /webinars/{webinarId}/polls': getWebinarsWebinarIdPolls,
  'POST /webinars/{webinarId}/polls': postWebinarsWebinarIdPolls,
  'GET /webinars/{webinarId}/registrants/questions': getWebinarsWebinarIdRegistrantsQuestions,
  'PATCH /webinars/{webinarId}/registrants/questions': patchWebinarsWebinarIdRegistrantsQuestions,
  'PUT /webinars/{webinarId}/registrants/status': putWebinarsWebinarIdRegistrantsStatus,
  'GET /webinars/{webinarId}/registrants/{registrantId}': getWebinarsWebinarIdRegistrantsRegistrantId,
  'DELETE /webinars/{webinarId}/registrants/{registrantId}': deleteWebinarsWebinarIdRegistrantsRegistrantId,
  'GET /webinars/{webinarId}/registrants': getWebinarsWebinarIdRegistrants,
  'POST /webinars/{webinarId}/registrants': postWebinarsWebinarIdRegistrants,
  'POST /webinars/{webinarId}/sip_dialing': postWebinarsWebinarIdSipDialing,
  'PUT /webinars/{webinarId}/status': putWebinarsWebinarIdStatus,
  'GET /webinars/{webinarId}/survey': getWebinarsWebinarIdSurvey,
  'DELETE /webinars/{webinarId}/survey': deleteWebinarsWebinarIdSurvey,
  'PATCH /webinars/{webinarId}/survey': patchWebinarsWebinarIdSurvey,
  'GET /webinars/{webinarId}/token': getWebinarsWebinarIdToken,
  'GET /webinars/{webinarId}/tracking_sources': getWebinarsWebinarIdTrackingSources,
  'GET /webinars/{webinarId}': getWebinarsWebinarId,
  'DELETE /webinars/{webinarId}': deleteWebinarsWebinarId,
  'PATCH /webinars/{webinarId}': patchWebinarsWebinarId,
  'DELETE /h323/devices/{deviceId}': deleteH323DevicesDeviceId,
  'PATCH /h323/devices/{deviceId}': patchH323DevicesDeviceId,
  'GET /h323/devices': getH323Devices,
  'POST /h323/devices': postH323Devices
};
