name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: |
          echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: config

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ steps.config.outputs.NVMRC }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.config.outputs.NVMRC }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run E2E Tests
        run: pnpm vitest
