name: Update OpenAPI

on:
  workflow_dispatch:
  schedule:
    - cron: '25 * * * *'

jobs:
  openapi-gen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build OpenAPI spec from PR
        run: pnpm generate

      - run: git add .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: 'Update OpenAPI Spec'
          committer: 'SferaDev <SferaDev@users.noreply.github.com>'
          title: '[OpenAPI] Spec updates'
          body: |
            This is an autogenerated PR to update the OpenAPI spec with the latest merged changes.

            Before merging these changes, please review the update and test it out.
          branch: openapi/update-spec
